### ISSUE TITLE
haproxy 1.9 http mode error

### ISSUE THREAD

**Issue by golubmikhail** [haproxy/haproxy#102]
Hello.

After upgrade haproxy to version 1.9.7 from FreeBSD port i give error ... in reverse proxy for MS Exchange.
ActiveSync, OWA - works.
MAPI stop working (https://docs.microsoft.com/en-us/exchange/clients/mapi-over-http/mapi-over-http?view=exchserver-2019)

Old version of haproxy 1.8 from FreeBSD port with option "no option http-tunnel" in "defaults" section work good.
After upgrade port haproxy to version 1.9.* - i give errors with this config.
The error was that in debug page https://mail.domain/mapi/emsmdb/?showdebug=yes i can see "Authentication: Negotiate" - it's from outside clients!
And "User:" changed ... - must be only logged username.
On haproxy 1.8 with "no option http-tunnel" parameter "Authentication:" always "NTLM".

On haproxy 1.9.8 i change option to "option http-tunnel" in defaults section and it solve a problem.

# haproxy -vv
HA-Proxy version 1.9.7 2019/04/25 - https://haproxy.org/
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-ignored-qualifiers -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wtype-limits -Wshift-negative-value -Wnull-dereference -DFREEBSD_PORTS
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_CPU_AFFINITY=1 USE_ACCEPT4=1 USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1 USE_PCRE_JIT=1

haproxy.conf:
global
    log /var/run/log local7 info
    user nobody
    group nobody
    daemon
    maxconn 20000
    pidfile /var/run/haproxy.pid
    external-check
    ssl-server-verify none
    tune.ssl.default-dh-param 2048
    ssl-default-bind-options no-sslv3 no-tls-tickets
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS

defaults
    mode http
    option dontlognull
    option http-keep-alive
    no option httpclose
    no option http-server-close
    no option forceclose
    no option http-tunnel
    balance leastconn
    default-server inter 3s rise 2 fall 3
    timeout client 600s
    timeout http-request 10s
    timeout connect 4s
    timeout server 60s

frontend fe
    bind 10.7.0.212:443 name https ssl crt /usr/local/etc/haproxy/cert/mail.domain.cer
    capture request header Host len 32
    capture request header User-Agent len 64
    capture response header Content-Length len 10
    log global
    log-format %ci\ %ft\ %b/%s\ %ST\ %B\ %hr\ {%sslv/%sslc}\ %HM\ \"%[capture.req.uri]\ %HV\"
    maxconn 15000
    option forwardfor
    acl ssl_connection ssl_fc
    acl host_mail hdr(Host) -i mail.domain
    acl path_slash path /
    acl path_autodiscover path_beg -i /Autodiscover/Autodiscover.xml
    acl path_activesync path_beg -i /Microsoft-Server-ActiveSync
    acl path_ews path_beg -i /ews/
    acl path_owa path_beg -i /owa/
    acl path_oa path_beg -i /rpc/rpcproxy.dll
    acl path_ecp path_beg -i /ecp/
    acl path_oab path_beg -i /oab/
    acl path_mapi path_beg -i /mapi/
    acl path_check path_end -i HealthCheck.htm
    http-request deny if path_check
    http-request deny if path_ecp
    http-request redirect scheme https code 302 unless ssl_connection
    http-request redirect scheme https code 301 if !{ ssl_fc }
    http-request redirect location /owa/ code 302 if path_slash host_mail
    use_backend be_exchange_https_autodiscover if path_autodiscover
    use_backend be_exchange_https_activesync if path_activesync
    use_backend be_exchange_https_ews if path_ews
    use_backend be_exchange_https_owa if path_owa
    use_backend be_exchange_https_oa if path_oa
    use_backend be_exchange_https_oab if path_oab
    use_backend be_exchange_https_mapi if path_mapi
    default_backend be_exchange_https_default

backend be_exchange_https_activesync
    reqadd X-Forwarded-Proto:\ https
    source 10.7.0.212
    option httpchk GET /Microsoft-Server-ActiveSync/HealthCheck.htm
    http-check expect string 200\ OK
    server e1 10.7.0.61:443 ssl verify none check source 10.7.0.212 weight 10
    server e2 10.7.0.62:443 ssl verify none check source 10.7.0.212 weight 10

backend be_exchange_https_autodiscover
    reqadd X-Forwarded-Proto:\ https
    source 10.7.0.212
    option httpchk GET /Autodiscover/HealthCheck.htm
    http-check expect string 200\ OK
    server e1 10.7.0.61:443 ssl verify none check source 10.7.0.212 weight 10
    server e2 10.7.0.62:443 ssl verify none check source 10.7.0.212 weight 10

backend be_exchange_https_ews
    reqadd X-Forwarded-Proto:\ https
    source 10.7.0.212
    option httpchk GET /EWS/HealthCheck.htm
    http-check expect string 200\ OK
    server e1 10.7.0.61:443 ssl verify none check source 10.7.0.212 weight 10
    server e2 10.7.0.62:443 ssl verify none check source 10.7.0.212 weight 10

backend be_exchange_https_mapi
    reqadd X-Forwarded-Proto:\ https
    source 10.7.0.212
    option httpchk GET /mapi/HealthCheck.htm
    http-check expect string 200\ OK
    timeout server 600s
    server e1 10.7.0.61:443 ssl verify none check source 10.7.0.212 weight 10
    server e2 10.7.0.62:443 ssl verify none check source 10.7.0.212 weight 10

backend be_exchange_https_oab
    reqadd X-Forwarded-Proto:\ https
    source 10.7.0.212
    option httpchk GET /OAB/HealthCheck.htm
    http-check expect string 200\ OK
    server e1 10.7.0.61:443 ssl verify none check source 10.7.0.212 weight 10
    server e2 10.7.0.62:443 ssl verify none check source 10.7.0.212 weight 10

backend be_exchange_https_oa
    reqadd X-Forwarded-Proto:\ https
    source 10.7.0.212
    option httpchk GET /RPC/HealthCheck.htm
    http-check expect string 200\ OK
    timeout server 600s
    server e1 10.7.0.61:443 ssl verify none check source 10.7.0.212 weight 10
    server e2 10.7.0.62:443 ssl verify none check source 10.7.0.212 weight 10

backend be_exchange_https_owa
    reqadd X-Forwarded-Proto:\ https
    source 10.7.0.212
    option httpchk GET /owa/HealthCheck.htm
    http-check expect string 200\ OK
    server e1 10.7.0.61:443 ssl verify none check source 10.7.0.212 weight 10
    server e2 10.7.0.62:443 ssl verify none check source 10.7.0.212 weight 10

backend be_exchange_https_default
    reqadd X-Forwarded-Proto:\ https
    source 10.7.0.212
    timeout server 60s
    server e1 10.7.0.61:443 ssl verify none check source 10.7.0.212 weight 10
    server e2 10.7.0.62:443 ssl verify none check source 10.7.0.212 weight 10

**Comment by capflam** [comment]
I don't know much about MS Exchange and how it works. I really don't know how the debug page figure out the NTLM is possible or not. If you have some details, it could help. Have you some significant differences in logs between HAProxy 1.8 and 1.9 ? 

BTW, the HTTP tunnelling is not a good idea, because only the first request will be analysed. 

Looking at your configuration, I'm surprised the NTLM ever worked. Without any kind of stickiness, connections to servers will always be loadbalanced. A common way to make the NTLM work is to enable the option `prefer-last-server`. Could you try to add this option to see if it fixes your issue ?

**Comment by golubmikhail** [comment]
HA-Proxy version 1.9.8 2019/05/13 - https://haproxy.org/
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-ignored-qualifiers -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wtype-limits -Wshift-negative-value -Wnull-dereference -DFREEBSD_PORTS
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_CPU_AFFINITY=1 USE_ACCEPT4=1 USE_REGPARM=1 USE_OPENSSL=1 USE_STATIC_PCRE=1 USE_PCRE_JIT=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1a-freebsd  20 Nov 2018
Running on OpenSSL version : OpenSSL 1.1.1a-freebsd  20 Nov 2018


Section in haproxy.conf:
defaults
    mode http
    option dontlognull
    option http-keep-alive
    no option httpclose
    no option http-server-close
    no option forceclose
    option http-tunnel
    balance leastconn
    default-server inter 3s rise 2 fall 3
    timeout client 600s
    timeout http-request 10s
    timeout connect 4s
    timeout server 60s

No errors with this config.
There is nothing unusual in the logs.
I can not conduct experiments in work time - more than 1000 employees.
A little later I check option prefer-last-server. Thanks.

**Comment by golubmikhail** [comment]
Hi.

Remove option for tunnelling and enable prefer-last-server helped me. Thanks.

24.05.2019 13:01, Christopher Faulet пишет:

**Comment by wtarreau** [comment]
This should be fixed in mainline by commit 250031e4 (not backported yet). The reason is the loss of the the prefer-last-server flag across requests in H2->H1 and in HTX mode since streams are totally independent.

**Comment by wtarreau** [comment]
now backported to 1.9, closing.

**Comment by bankexing** [comment]
exchange 2016 + outlook 2013 sp1, MAPI over HTTP is still not working when load balance by haproxy 2.0.x.
But haproxy 1.8.x is OK.
Authorization basic and ntlm are the same result.
