### ISSUE TITLE
HAProxy doesn't work with Apple M1—yet it ran without error

### ISSUE THREAD

**Issue by philipyoungg** [haproxy/haproxy#1020]
## Detailed description of the problem
On Apple M1
```
brew install haproxy
haproxy -f haproxy.cfg
```
It ran without any error. Connecting to the URL doesn't work though.
I tested the same thing on Intel-based Macbook, it ran perfectly.

## Expected behavior

Should run on M1, just like on Intel

## Steps to reproduce the behavior

1. Just start `HAProxy`

## Do you have any idea what may have caused this?
Probably because of ARM architecture?

## Do you have an idea on how to solve the issue?
Nope!

## More info
Haproxy via docker works on M1.

**Comment by TimWolla** [comment]
You left out one of the most important parts of the template: The output of `haproxy -vv`, and also your configuration.

**Comment by philipyoungg** [comment]
@TimWolla apologize. 

## Config
```
global
        maxconn 200000

defaults
        mode http
        timeout connect 10s
        timeout client 30s
        timeout server 30s
        maxconn 200000

frontend all
        bind *:8000
        stats uri /haproxy?stats
        default_backend backends

backend backends
        balance leastconn
        server s1 192.168.1.200:9000 maxconn 10000 check
        server s2 192.168.1.200:9001 maxconn 10000 check
        server s3 192.168.1.200:9002 maxconn 10000 check
        server s4 192.168.1.200:9003 maxconn 10000 check
```
## `haproxy -vv`
```
HA-Proxy version 2.3.2-d522db7 2020/11/28 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.2.html
Running on: Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
Build options :
  TARGET  = generic
  CPU     = generic
  CC      = clang
  CFLAGS  =
  OPTIONS = USE_KQUEUE=1 USE_PCRE=1 USE_POLL=1 USE_THREAD=1 USE_OPENSSL=1 USE_ZLIB=1
  DEBUG   =

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE -LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL -LUA -FUTEX -ACCEPT4 -CLOSEFROM +ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using:
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): no
Built with clang compiler version 12.0.0 (clang-1200.0.32.28)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by devnexen** [comment]
Hopes this help, but I recently got a M1 and compiled with same options with similar config file. and it works. haproxy works alright on ARM in general, maybe incoming connections settings or something else is at play.

**Comment by philipyoungg** [comment]
@devnexen interesting. How do you install it? With `homebrew` over rosetta? I installed it with experimental native ARM `homebrew`.

Mine works on both (intel and arm). It didn't scream any error.

The difference with no backend opened:
- Intel screams that all of the backends are not open, 
- ARM doesn't show anything

**Comment by devnexen** [comment]
I tried both via homebrew for ARM and compiled manually too (did not try with Rosetta but another Mac with real Intel). The ARM version also showed me at first backend unavailable.

**Comment by philipyoungg** [comment]
@devnexen thank you. I wonder what my issue is. It's a fresh install and it was installed on `/opt/homebrew/bin/haproxy`.

Can you elaborate what you meant with "compiled manually"? Do you mean installing it outside homebrew?

**Comment by devnexen** [comment]
Yes that is it outside homebrew but does not really matter as the homebrew version worked same as you fresh install.

**Comment by tomciopp** [comment]
@philipyoungg Running into similar issues with a new M1 Mac. Activity Monitor shows the process running at 98.4% CPU utilization, no errors are showing up in the console. The other thing I've noticed is I do not get the popup notification on the new M1 mac to "allow incoming connections", so maybe there is a firewall issue I'm not aware of.

### Here is the output of haproxy -vv
```bash
HA-Proxy version 2.3.2-d522db7 2020/11/28 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.2.html
Running on: Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64
Build options :
  TARGET  = generic
  CPU     = generic
  CC      = clang
  CFLAGS  =
  OPTIONS = USE_KQUEUE=1 USE_PCRE=1 USE_POLL=1 USE_THREAD=1 USE_OPENSSL=1 USE_ZLIB=1
  DEBUG   =

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE -LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL -LUA -FUTEX -ACCEPT4 -CLOSEFROM +ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using:
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): no
Built with clang compiler version 12.0.0 (clang-1200.0.32.28)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Here is my config file

```bash
global
  log 127.0.0.1 local0 info
  stats timeout 30s
  maxconn 1024

defaults
  mode tcp
  log global
  option httplog
  option http-server-close
  option dontlognull
  option redispatch
  option contstats
  retries 3
  backlog 10000
  timeout connect  5000
  timeout client  50000
  timeout server  50000
  timeout tunnel 3600s
  timeout http-keep-alive 1s
  timeout http-request 15s
  timeout queue 30s
  timeout tarpit 60s

frontend device
  bind 0.0.0.0:8443
  option tcplog
  mode tcp
  default_backend backend

backend backend
  mode tcp
  server srv-1 127.0.0.1:4443 check send-proxy-v2-ssl
```

**Comment by wtarreau** [comment]
Please note that an issue affecting some modern ARM CPUs (including Graviton2 and likely the M1) was fixed and backported into 2.3 as commit 3027cdc ("BUG/MEDIUM: task: close a possible data race condition on a tasklet's list link") after the one you're testing.

Oh, in addition we have commit 63ee2818 in 2.4-dev that adresses an issue with the assembler on macos and which will make compare-and-swap fail. It's not marked as a bug but definitely needs to be backported. I guess I'll have to work on preparing backports today :-/

Please just try the latest 2.4-dev to confirm it's OK for you, so that we're certain not to miss anything for a next 2.3.

**Comment by devnexen** [comment]
My bad the homebrew package does not work indeed, but only the new 2.4-dev version.

**Comment by tomciopp** [comment]
Hmm downloaded 2.4-dev4, and am still getting errors. It also looks like the following keyword is not valid: `send-proxy-v2-ssl`.

Downloaded and ran
```bash
make TARGET=osx
```

```bash
[NOTICE] 004/014716 (18872) : haproxy version is 2.4-dev4-4d71176
[ALERT] 004/014716 (18872) : parsing [/opt/homebrew/etc/haproxy.cfg:33] : 'server s1' unknown keyword 'send-proxy-v2-ssl'. Registered keywords :
    [ ALL] backup [dflt_ok]
    [ ALL] cookie <arg> [dflt_ok]
    [ ALL] disabled [dflt_ok]
    [ ALL] enabled [dflt_ok]
    [ ALL] id <arg>
    [ ALL] max-reuse <arg> [dflt_ok]
    [ ALL] namespace <arg> [dflt_ok]
    [ ALL] no-backup [dflt_ok]
    [ ALL] no-send-proxy [dflt_ok]
    [ ALL] no-send-proxy-v2 [dflt_ok]
    [ ALL] no-tfo [dflt_ok]
    [ ALL] non-stick [dflt_ok]
    [ ALL] observe <arg> [dflt_ok]
    [ ALL] pool-low-conn <arg> [dflt_ok]
    [ ALL] pool-max-conn <arg> [dflt_ok]
    [ ALL] pool-purge-delay <arg> [dflt_ok]
    [ ALL] proto <arg> [dflt_ok]
    [ ALL] proxy-v2-options <arg> [dflt_ok]
    [ ALL] redir <arg> [dflt_ok]
    [ ALL] send-proxy [dflt_ok]
    [ ALL] send-proxy-v2 [dflt_ok]
    [ ALL] source <arg> [dflt_ok]
    [ ALL] stick [dflt_ok]
    [ ALL] tfo [dflt_ok]
    [ ALL] track <arg> [dflt_ok]
    [ ALL] socks4 <arg> [dflt_ok]
    [ CHK] addr <arg> [dflt_ok]
    [ CHK] agent-addr <arg> [dflt_ok]
    [ CHK] agent-check [dflt_ok]
    [ CHK] agent-inter <arg> [dflt_ok]
    [ CHK] agent-port <arg> [dflt_ok]
    [ CHK] agent-send <arg> [dflt_ok]
    [ CHK] check [dflt_ok]
    [ CHK] check-proto <arg> [dflt_ok]
    [ CHK] check-send-proxy [dflt_ok]
    [ CHK] check-via-socks4 [dflt_ok]
    [ CHK] no-agent-check [dflt_ok]
    [ CHK] no-check [dflt_ok]
    [ CHK] no-check-send-proxy [dflt_ok]
    [ CHK] rise <arg> [dflt_ok]
    [ CHK] fall <arg> [dflt_ok]
    [ CHK] inter <arg> [dflt_ok]
    [ CHK] fastinter <arg> [dflt_ok]
    [ CHK] downinter <arg> [dflt_ok]
    [ CHK] port <arg> [dflt_ok]
```

If I use the option `send-proxy-v2` instead haproxy states that the configuration file is ok. However if I try to start the server again, it hangs and eats up the CPU still. (Running M1 macbook air - 8 core version if that makes a difference)

**Comment by wtarreau** [comment]
That's expected, the fix was merged 2 days after dev4 (commit 63ee2818). If you take the latest nightly snapshot or latest git tree you'll have it.

**Comment by tomciopp** [comment]
@wtarreau Oh ok, let me check that out instead. Will report back if it works or there are still issues.

**Comment by tomciopp** [comment]
Ok I've got it working when we make from `master`. It does look like `send-proxy-v2-ssl` is no longer a keyword. I will send a PR to @cbonte to update the configuration docs accordingly. 

As always thank you @wtarreau for being the best.

**Comment by wtarreau** [comment]
Great, many thanks for the confirmation. You don't need to bother @cbonte for the doc, he maintains the doc converter, but the contents should be part of the patches which add/remove features. However, I've just checked, and the keyword was not removed. I suspect you've simply forgotten to enable SSL in your build :-)

We're a bit lagging behind in terms of versions, as usual in this period of the year. I'll focus a bit on what's missing to issue a new bunch of versions.

**Comment by tomciopp** [comment]
@wtarreau If you take a look at the parse error I included above, it's not listed in the available keywords. It's also missing the `-cn` version as well. Unless I'm completely mistaken (quite likely) I think this may be a bug.

**Comment by wtarreau** [comment]
No, this is really likely because you didn't enable SSL (hence the keywords that come with it). When I pass your config through haproxy -c, it says `Configuration file is valid`.

**Comment by tomciopp** [comment]
@wtarreau If I run `haproxy -c` on my intel mac it says the configuration file is valid. When I do it on the m1 mac I get a parse error.

**Comment by tomciopp** [comment]
I should note haproxy should not be terminating the ssl in my setup, the webserver should be.

**Comment by wtarreau** [comment]
The difference definitely are the build options. What options did you use when building it yourself ? You'll see them in haproxy -vv.

**Comment by lukastribus** [comment]
> Downloaded and ran
> 
> ```shell
> make TARGET=osx
> ```

You are specifically compiling without SSL support here, therefor SSL options like `send-proxy-v2-ssl` will not be available. This has nothing to do with Intel vs ARM, but with or without an certain build option. SSL options (and other options as well) will be removed from the supported options, when compiled without the required library, because they are unusable.

Add `USE_OPENSSL=1` to your make command as per `INSTALL`, and you will see those SSL options.

    make clean; make TARGET=osx USE_OPENSSL=1

**Comment by tomciopp** [comment]
@lukastribus Thanks for the info, that makes sense. However when one mole gets whacked another one pops right back up.

```bash
➜  make clean; make TARGET=osx USE_OPENSSL=1
  CC      src/ev_poll.o
  CC      src/ev_kqueue.o
  CC      src/ssl_sample.o
In file included from src/ssl_sample.c:27:
In file included from include/haproxy/obj_type.h:26:
In file included from include/haproxy/applet-t.h:31:
In file included from include/haproxy/proxy-t.h:35:
In file included from include/haproxy/backend-t.h:30:
In file included from include/haproxy/lb_map-t.h:26:
In file included from include/haproxy/server-t.h:32:
In file included from include/haproxy/check-t.h:22:
In file included from include/haproxy/connection-t.h:34:
In file included from include/haproxy/listener-t.h:37:
include/haproxy/openssl-compat.h:5:10: fatal error: 'openssl/bn.h' file not found
#include <openssl/bn.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [src/ssl_sample.o] Error 1
```

```bash
➜  openssl version
LibreSSL 2.8.3
```

**Comment by wtarreau** [comment]
Ah so you don't have the SSL development packages installed. Usually it's called "openssl-devel" or something like this. Since you're on libressl, it might as well be called "libressl-devel". I have no idea how packages are managed on Mac however.

**Comment by diov** [comment]
@tomciopp You could add `SSL_LIB` and `SSL_INC` arguments as a workaround.
```
make clean; make TARGET=osx USE_OPENSSL=1 SSL_LIB=/usr/local/opt/openssl@1.1/lib SSL_INC=/usr/local/opt/openssl@1.1/include
```
