### ISSUE TITLE
Delete from ACL is O(n)

### ISSUE THREAD

**Issue by khvzak** [haproxy/haproxy#1052]
## Detailed description of the problem
Removing value from a large ACL takes long time and makes not suitable for runtime updates. Probably because the complexity is ~O(n).
Also during the procedure haproxy consumes 100% CPU and slow down requests.

## Expected behavior
O(1) ideally or O(logN) in worst case.

## Steps to reproduce the behavior

```
# Generate a large file with 10M records and 315MB size.
$ perl -lE "open F,'>acl.txt'; @d=('a'..'z','A'..'Z'); print F (map { @d[rand(@d)] } 1..32) for 1..10_000_000;"

# Run haproxy
$ haproxy -f haproxy1.cfg

# In another tab/session
$ time head -n 10 acl.txt | xargs -n1 -I{} curl -I -X GET -H 'x-acl-del: {}' http://127.0.0.1:8080
....
real	0m20.020s
user	0m0.032s
sys	0m0.067s
```

About **2 sec** to delete one entry on **2.9 GHz Quad-Core Intel Core i7**.

## What is your configuration?

```
defaults
    mode http
    option httplog
    log stdout format raw daemon info
    timeout connect 1s
    timeout client 3s
    timeout server 3s

listen http-in
    bind 127.0.0.1:8080
    acl is_matched hdr(x-val) -m str -f acl.txt
    acl is_del hdr(x-acl-del) -m found
    http-request del-acl(acl.txt) %[req.hdr(x-acl-del)] if is_del
    http-request return status 200 if is_del
    http-request deny
```

## Output of `haproxy -vv` and `uname -a`

```
$ haproxy -vv
HA-Proxy version 2.2.7-f10629d 2021/01/08 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.7.html
Running on: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
Build options :
  TARGET  = osx
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-string-plus-int -Wtype-limits -Wshift-negative-value -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_THREAD=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   = 

Feature list : -EPOLL +KQUEUE -NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL +LUA -FUTEX -ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using:
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with clang compiler version 12.0.0 (clang-1200.0.32.28)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

$ uname -a
Darwin C02V37K2HTD8 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
```

**Comment by wtarreau** [comment]
Yes, this is known and was addressed in 2.3. The root cause of the problem is that keys are multiply-indexed and we need to visit all their indexed places, but the links were only between the call places so it was not always possible to directly access them depending on the indexing. In 2.3 the indexing method changed so that for each input key we have a direct pointer to all use places and we're able to instantly delete them. For 2.5 we could further improve this, maybe even 2.4, but that would only be used to save memory, which is less critical.

Could you please retry on 2.3 and confirm that it's OK for you ? I've already thought about backporting these changes but I'd rather avoid if this serves only a few people and the risk is non-null.

**Comment by khvzak** [comment]
Results from the `HA-Proxy version 2.3.4-10189c9 2021/01/13 - https://haproxy.org/`

```
$ time head -n 10 acl.txt | xargs -n1 -I{} curl -I -X GET -H 'x-acl-del: {}' http://127.0.0.1:8080
HTTP/1.1 200 OK
content-length: 0
...
real	0m24.698s
user	0m0.038s
sys	0m0.081s
```

Seems not fixed :( I'll try the latest master later today

**Comment by wtarreau** [comment]
Just checked and I was wrong, the dev was done before the 2.3 release but too late and too touchy to be merged at the last minute, so it's only in 2.4.

Regardless I'm interested in your feedback! By the way, could you please issue a `wc -l` on acl.txt just to get an idea of the complexity ? My tests were run with up to 20M IP addresses per file.

**Comment by khvzak** [comment]
`acl.txt` has exactly 10,000,000 records and I used the following command to generate it:
```
perl -lE "open F,'>acl.txt'; @d=('a'..'z','A'..'Z'); print F (map { @d[rand(@d)] } 1..32) for 1..10_000_000;"
```

Tested on `2.4-dev5-e3bdc8-29` (latest master) with these results:
```
$ time head -n 10 acl.txt | xargs -n1 -I{} curl -I -X GET -H 'x-acl-del: {}' http://127.0.0.1:8080
...
real	0m1.237s
user	0m0.032s
sys	0m0.060s
```
Much better. I'm happy that the issue finally has been addressed.

**Comment by wtarreau** [comment]
Great, thank you. Do you currently have a production requirement on this making it a showstopper for 2.3, or can you reasonably wait for 2.4 to be released (a few months) ?

**Comment by khvzak** [comment]
I can wait for 2.4 (plus this is going to be a LTS version), thanks. Currently I use my own ACL implementation built on top of the Lua API, Rust binary code and rely on `HAPROXY_CFGFILES` exported variable.
It works very fast on large scale despite the global Lua lock across threads.

**Comment by wtarreau** [comment]
Great, thanks. The global Lua lock has little effect until a sudden wall that happens once you start to consume too much time in Lua from too many threads. But once you move to 2.4, you'll benefit from the new `lua-load-per-thread` directive which allows all thread to run their own lockless Lua state, which is perfectly suited to such things.
I think we can close this issue now then.
