### ISSUE TITLE
Connection leak with client FIN before response

### ISSUE THREAD

**Issue by jaroslawr** [haproxy/haproxy#1362]
### Detailed Description of the Problem

HAProxy 2.4.3 over time accumulates CLOSE-WAIT connections that look like this in `ss -tp`:

```
Recv-Q     Send-Q         Local Address:Port             Peer Address:Port      Process                                                                        
1          0              4.3.2.1:http             1.2.3.4:34904      users:(("haproxy",pid=3997921,fd=10766)) 
```

These appear to never get cleaned up. `show fd 10766` gives:

```
  10766 : st=0x001122(cl HeopI W:sRa R:sRa) tmask=0x1000000000 umask=0x0 owner=0x7f32a4b15bf0 iocb=0x55ffbdc56c20(sock_conn_iocb) back=0 cflg=0x80001300 fam=ipv4 lport=80 rport=34904 fe=http mux=H1 ctx=0x7f32dc18cb50 h1c.flg=0x2200 .sub=0 .ibuf=5@0x7f32dc0a93b0+0/32768 .obuf=0@(nil)+0/0 h1s=0x7f32dc189d40 h1s.flg=0x90 .req.state=MSG_CHUNK_SIZE .res.state=MSG_RPBEFORE .meth=POST status=0 .cs.flg=0x00100600 .cs.data=0x7f32dc08fab0 .subs=(nil) xprt=RAW
```

Looking at the corresponding traffic in tcpdump, this connection received a POST request and then the client sent a FIN+ACK before a response was produced. Maybe there is more to it, but so far I haven't noticed anything else special about what happens on those leaked connections.

### Expected Behavior

HAProxy should close a connection finished on the TCP level through sending a FIN packet, even when FIN arrives before response is sent.

### Steps to Reproduce the Behavior

1. Send HTTP request
2. Send TCP FIN before response arrives

### What is your configuration?

```haproxy
global
        user haproxy
        group haproxy

        nbthread 64
        cpu-map auto:1/1-64 0-31 64-95

        maxconn 120000
        hard-stop-after 10s

        tune.bufsize 32768
        tune.ssl.default-dh-param 2048
        tune.ssl.cachesize 10000000
        tune.ssl.lifetime 3600

        log /dev/log local0 info

defaults
        mode http

        log global
        option httplog

        option forwardfor
        option http-buffer-request

        maxconn 110000

        retries 0
        no option redispatch

        timeout client 30000
        timeout server 500
        timeout connect 25
        timeout queue 25

frontend http
        bind *:80

        default_backend xyz

frontend https
        bind *:443 ssl crt /etc/haproxy/abcd.pem alpn h2,http/1.1

        default_backend xyz

backend xyz
        balance leastconn
        option httpchk
        http-check send meth HEAD uri /healthcheck
        default-server check inter 1000 maxqueue 1

        server xyz_101.net_1234 xyz_101.net:1234 weight 10 maxconn 10
        ...
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.3-4dd5a5a 2021/08/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.3.html
Running on: Linux 5.10.0-1026-oem #27-Ubuntu SMP Thu May 6 07:19:13 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by wtarreau** [comment]
Hi Jaroslaw,

That's not cool, just like with each and every new version it was supposed to be totally addressed. Ah this time it's in H1 not H2, this changes! Did you notice this recently or are you aware of a regression since a recent version ?

**Comment by jaroslawr** [comment]
@wtarreau Looking at our HAProxy version migration history and socket stats it looks like this might have started with HAProxy 2.3.0.

**Comment by wtarreau** [comment]
This will definitely help, thank you!

**Comment by wtarreau** [comment]
Now I understand the problem. It's *exactly* the same as the one that was causing CLOSE_WAIT on H2: some partial messages followed by a FIN cannot be parsed but the data remains present and the FIN is not considered. It was addressed in H2 by significantly revisiting the loop, but in H1 it's trickier as it's called from the two sides, and if I do it wrong I will cause spurious connection aborts. Do you mind if I wait for @capflam's return (~1 week or so) to discuss this with him and avoid making things worse ? In case this is causing you severe trouble, just PM me and we'll try to figure together a temporary workaround.

**Comment by jaroslawr** [comment]
@wtarreau It can wait, thanks for looking into it. I reported one more issue: https://github.com/haproxy/haproxy/issues/1377 Judging by what you just wrote, maybe it's in the same area?

**Comment by wtarreau** [comment]
It's possible, indeed.

**Comment by capflam** [comment]
I'm able to reproduce the issue quite easily. @wtarreau analysis is correct, I'm investigating to find the right way to fix the bug. In the mean time, a good way to mitigate the problem is to set the `http-request` timeout.

**Comment by jaroslawr** [comment]
@capflam Thanks, adding `timeout http-request` fixed the problem.

**Comment by capflam** [comment]
Thanks for the feedback @jaroslawr. It works but it is a workaround. I finally fixed the issue, or I hope so. I attached the patch. It may be applied to the 2.4 if you want to test it.

I will push it to the 2.5 but I'll wait a bit before backporting it to be sure there is no regression.

~~0001-BUG-MEDIUM-mux-h1-Adjust-conditions-to-ask-more-spac.patch.txt~~

**Comment by capflam** [comment]
Here is a V2 of the patch above. I've found a blocking condition on trailers parsing that should be handled by this one.

[0001-BUG-MEDIUM-mux-h1-Adjust-conditions-to-ask-more-spac.patch.V2.txt](https://github.com/haproxy/haproxy/files/7196263/0001-BUG-MEDIUM-mux-h1-Adjust-conditions-to-ask-more-spac.patch.V2.txt)

**Comment by jaroslawr** [comment]
@capflam I deployed the V2 patch without `timeout http-request` and then unfortunately CLOSE_WAIT still seem to accumulate.

**Comment by capflam** [comment]
Thanks for the info. I'm bit annoyed because I was pretty sure it would fix your issue. I have a patchset on top of this one that may help. But I want to understand why this one does not work because I don't want to hide a bug with the others patches.

**Comment by capflam** [comment]
Just to be sure, `show fd` of stuck connections are still the same than the one provided in the report ?

**Comment by jaroslawr** [comment]
@capflam I guess my original bug report included too few example fds - on 2.4.3 without any patches, in addition to connections with `.req.state=MSG_CHUNK_SIZE`, there are also connections like this:

```
   4708 : st=0x001122(cl HeopI W:sRa R:sRa) tmask=0x40000 umask=0x0 owner=0x7fbdf822cc50 iocb=0x55bf3f837c90(sock_conn_iocb) back=0 cflg=0x80001300 fam=ipv4 lport=80 rport=52141 fe=http mux=H1 ctx=0x7fbdb01d9bb0 h1c.flg=0x2200 .sub=0 .ibuf=2@0x7fbdb08b32b0+0/32768 .obuf=0@(nil)+0/0 h1s=0x7fbdb00c02a0 h1s.flg=0x90 .req.state=MSG_TRAILERS .res.state=MSG_RPBEFORE .meth=POST status=0 .cs.flg=0x00100600 .cs.data=0x7fbdb04673b0 .subs=(nil) xprt=RAW
```

```
   9520 : st=0x001122(cl HeopI W:sRa R:sRa) tmask=0x100000000000000 umask=0x0 owner=0x7fbda0058040 iocb=0x55bf3f837c90(sock_conn_iocb) back=0 cflg=0x80001300 fam=ipv4 lport=80 rport=55176 fe=http mux=H1 ctx=0x7fbda093a940 h1c.flg=0x2200 .sub=0 .ibuf=7@0x7fbdb8732650+0/32768 .obuf=0@(nil)+0/0 h1s=0x7fbe401cada0 h1s.flg=0x90 .req.state=MSG_CHUNK_CRLF .res.state=MSG_RPBEFORE .meth=POST status=0 .cs.flg=0x00100600 .cs.data=0x7fbdb82eeda0 .subs=(nil) xprt=RAW
```

With your patch, there are no longer any CLOSE-WAIT connections with `.req.state=MSG_CHUNK_SIZE`, but those with `.req.state=MSG_TRAILERS` and `.req.state=MSG_CHUNK_CRLF` are still there, for example (these below are from HAProxy with your patch, just in case they differ in any way from these from 2.4.3):

```
 23769 : st=0x001122(cl HeopI W:sRa R:sRa) tmask=0x1000000000000 umask=0x0 owner=0x7fbe3c42e360 iocb=0x55bf3f837c90(sock_conn_iocb) back=0 cflg=0x80001300 fam=ipv4 lport=80 rport=35840 fe=http mux=H1 ctx=0x7fbd681eaf90 h1c.flg=0x2200 .sub=0 .ibuf=2@0x7fbd743a8110+0/32768 .obuf=0@(nil)+0/0 h1s=0x7fbda07a9e70 h1s.flg=0x90 .req.state=MSG_TRAILERS .res.state=MSG_RPBEFORE .meth=POST status=0 .cs.flg=0x00100600 .cs.data=0x7fbd740c9da0 .subs=(nil) xprt=RAW
```

```
    271 : st=0x001122(cl HeopI W:sRa R:sRa) tmask=0x10000 umask=0x0 owner=0x7fbdf8584470 iocb=0x55bf3f837c90(sock_conn_iocb) back=0 cflg=0x80001300 fam=ipv4 lport=80 rport=43217 fe=http mux=H1 ctx=0x7fbdf8040de0 h1c.flg=0x2200 .sub=0 .ibuf=7@0x7fbdfc879670+0/32768 .obuf=0@(nil)+0/0 h1s=0x7fbd681aa270 h1s.flg=0x90 .req.state=MSG_CHUNK_CRLF .res.state=MSG_RPBEFORE .meth=POST status=0 .cs.flg=0x00100600 .cs.data=0x7fbdfc56aec0 .subs=(nil) xprt=RAW
```

**Comment by capflam** [comment]
Ok thanks. it is really helpful. I'm digging.

**Comment by capflam** [comment]
I found the issue, I must rework my patch.

**Comment by capflam** [comment]
@jaroslawr,  I pushed several patches that should fix this issue. For now, everything was backported in the 2.4 next branch (http://git.haproxy.org/?p=haproxy-2.4.git;a=shortlog;h=refs/heads/next). You can try it or just get the attached series on top of the 2.4:

[0001-BUG-MEDIUM-mux-h1-Adjust-conditions-to-ask-more-spac.patch.txt](https://github.com/haproxy/haproxy/files/7223875/0001-BUG-MEDIUM-mux-h1-Adjust-conditions-to-ask-more-spac.patch.txt)
[0002-BUG-MEDIUM-stream-int-Notify-stream-that-the-mux-wan.patch.txt](https://github.com/haproxy/haproxy/files/7223877/0002-BUG-MEDIUM-stream-int-Notify-stream-that-the-mux-wan.patch.txt)
[0003-BUG-MEDIUM-stream-Stop-waiting-for-more-data-if-SI-i.patch.txt](https://github.com/haproxy/haproxy/files/7223878/0003-BUG-MEDIUM-stream-Stop-waiting-for-more-data-if-SI-i.patch.txt)
[0004-MINOR-stream-int-Set-CO_RFL-transient-persistent-fla.patch.txt](https://github.com/haproxy/haproxy/files/7223879/0004-MINOR-stream-int-Set-CO_RFL-transient-persistent-fla.patch.txt)
[0005-MINOR-htx-Add-an-HTX-flag-to-know-when-a-message-is-.patch.txt](https://github.com/haproxy/haproxy/files/7223880/0005-MINOR-htx-Add-an-HTX-flag-to-know-when-a-message-is-.patch.txt)
[0006-MINOR-htx-Add-a-function-to-know-if-the-free-space-w.patch.txt](https://github.com/haproxy/haproxy/files/7223881/0006-MINOR-htx-Add-a-function-to-know-if-the-free-space-w.patch.txt)
[0007-BUG-MEDIUM-stream-int-Defrag-HTX-message-in-si_cs_re.patch.txt](https://github.com/haproxy/haproxy/files/7223882/0007-BUG-MEDIUM-stream-int-Defrag-HTX-message-in-si_cs_re.patch.txt)
[0008-MINOR-stream-int-Notify-mux-when-the-buffer-is-not-s.patch.txt](https://github.com/haproxy/haproxy/files/7223883/0008-MINOR-stream-int-Notify-mux-when-the-buffer-is-not-s.patch.txt)

I really hope I identified the right bug.

**Comment by jaroslawr** [comment]
@capflam I test the version from git next branch, works great now :+1: Thanks!

**Comment by capflam** [comment]
Cool, thanks for the test ! I'll merge it in 2.4-master soon.

**Comment by jaroslawr** [comment]
@capflam I ran into a possibly related problem with another proxy with HAProxy 2.4.3 - I can't tell if its something fixed by the changes you have made in 2.4.5, hence I report it here. Some of the HAProxy threads started spinning at 100% and stay like this and apparently they process a CLOSE_WAIT connection, for example:

```
  Thread 6 : id=0x7f4918547700 act=1 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=0 wantrdv=0
             cpu_ns: poll=69514387069074 now=69514387307844 diff=238770
             curr_task=0x7f48cb59b910 (tasklet) calls=238154765
               fct=0x557c3a731690(h2_io_cb) ctx=0x7f4908535f50
```

```
grep 0x7f4908535f50 show_fd
  16723 : st=0x001122(cl HeopI W:sRa R:sRa) tmask=0x20 umask=0x0 owner=0x7f48b7c40e70 iocb=0x557c3a851c20(sock_conn_iocb) back=0 cflg=0x80041300 fam=ipv4 lport=443 rport=10529 fe=xyz.net mux=H2 ctx=0x7f4908535f50 h2c.st0=FRP .err=0 .maxid=1 .lastid=-1 .flg=0x30000 .nbst=0 .nbcs=0 .fctl_cnt=0 .send_cnt=0 .tree_cnt=0 .orph_cnt=0 .sub=0 .dsi=3 .dbuf=603@0x7f4858fffe00+48/32768 .msi=-1 .mbuf=[1..1|32],h=[0@(nil)+0/0],t=[0@(nil)+0/0] xprt=SSL xprt_ctx=0x7f48f6c44600 xctx.st=0 .xprt=RAW .wait.ev=0 .subs=(nil) .sent_early=0 .early_in=0
```

```
ss -taneiop dport 10529 | grep 16723
CLOSE-WAIT   0        0          1.2.3.4:443       4.3.2.1:10529    users:(("haproxy",pid=2655531,fd=16723)) uid:10320 ino:2805918363 sk:20 -->
```

```
  Thread 3 : id=0x7f4919d4a700 act=1 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=0
             stuck=0 prof=0 harmless=0 wantrdv=0
             cpu_ns: poll=65809066297023 now=65809066449393 diff=152370
             curr_task=0x7f4910c03010 (tasklet) calls=3966571079
               fct=0x557c3a731690(h2_io_cb) ctx=0x7f4841536b90
```

```
grep 0x7f4841536b90 show_fd
 86172 : st=0x001122(cl HeopI W:sRa R:sRa) tmask=0x4 umask=0x0 owner=0x7f48bd15da40 iocb=0x557c3a851c20(sock_conn_iocb) back=0 cflg=0x80041300 fam=ipv4 lport=443 rport=10401 fe=xyz.net mux=H2 ctx=0x7f4841536b90 h2c.st0=FRP .err=0 .maxid=1 .lastid=-1 .flg=0x30000 .nbst=0 .nbcs=0 .fctl_cnt=0 .send_cnt=0 .tree_cnt=0 .orph_cnt=0 .sub=0 .dsi=3 .dbuf=603@0x7f484222a130+48/32768 .msi=-1 .mbuf=[1..1|32],h=[0@(nil)+0/0],t=[0@(nil)+0/0] xprt=SSL xprt_ctx=0x7f48c02d2130 xctx.st=0 .xprt=RAW .wait.ev=0 .subs=(nil) .sent_early=0 .early_in=0
```

```
ss -taneiop dport 10401 | grep 86172
CLOSE-WAIT   0        0          1.2.3.4:443       4.3.2.1:10401    users:(("haproxy",pid=2655531,fd=86172)) uid:10320 ino:2799130274 sk:3007 -->
```

Flamegraph of just the busy thread:
[stuck_thread.zip](https://github.com/haproxy/haproxy/files/7290710/stuck_thread.zip)

**Comment by capflam** [comment]
It is not the same problem. In fact, it is another occurrence of the issue #1328. Here I suspect the `read0` is not properly handled when parsing CONTINUATION frames. I must do a review with Willy to be sure.

**Comment by capflam** [comment]
@jaroslawr, I pushed a patch to 2.5-DEV to fix the spinning loop in the H2 mux;

* 485da0b05 BUG/MEDIUM: mux_h2: Handle others remaining read0 cases on partial frames

It will be backported. But in the mean time, it the bug is too annoying (or just to validate the fix) you can apply it on the 2.4.

**Comment by jaroslawr** [comment]
@capflam :+1: Thanks!
