### ISSUE TITLE
Truncated http json response data (possible regression in 2.3.15)

### ISSUE THREAD

**Issue by bdentino** [haproxy/haproxy#1450]
### Detailed Description of the Problem

We have a production deployment using dockerized haproxy for ingress. We've been running the `2.3-alpine` tag with no problems for some time. A few days ago we started noticing strange problems cropping up across various services that use these containers for load balancing. Specifically, responses with 'larger' json payloads (on the order of 100s of kilobytes, not particularly huge) would occasionally be truncated without any otherwise abnormal socket termination. Because the socket would close normally the application would try to parse the response and fail because it was incomplete. 

HAProxy logs look perfectly normal and the payload size appears to indicate that the full response was indeed passed through, but client logs indicated that fewer bytes were actually being read.

When I changed our applications to bypass HAProxy and go directly to the backend service, the problem disappeared.
It also seemed to disappear when I enabled gzip between the server/client while keeping HAProxy in the middle (presumably because the compressed payloads were smaller).

I noticed 2.3.15 was released around the time this started happening so I pinned our image back to 2.3.14 and it appears to have solved the problem.

### Expected Behavior

Responses should not be truncated.

### Steps to Reproduce the Behavior

This is difficult to reliably reproduce but it seems to be a problem with 2.3.15 and large json payloads.

### Do you have any idea what may have caused this?

Possible regression between 2.3.14 and 2.3.15

### What is your configuration?

```haproxy
Heavily truncated/redacted configuration:


global
  log stdout format raw local0 info
  tune.ssl.default-dh-param 2048
  maxconn 4096

defaults
  timeout connect 1000
  timeout client  50000
  timeout server  50000

  option http-ignore-probes
  option redispatch
  retries 3
  retry-on conn-failure

frontend 443_https
  mode http
  log stdout local0
  option httplog
  bind *:443 ssl crt cert.pem alpn h2,http/1.1

  acl use_backend always_true 

  use backend1 if use_backend

backend backend1
  mode http
  retries 5
  option redispatch

  default-server check inter 2000 fastinter 500 downinter 500 rise 2 fall 3
  server x.x.x.x x.x.x.x:80 
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.3.15-b10bdb0 2021/11/04 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.15.html
Running on: Linux 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=6).
Built with OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.3.1 20210424

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```

**Comment by capflam** [comment]
I pushed a patch that should hopefully fix this issue. If possible, it could be good to confirm it really fixes it. To do so, you must apply this small patch on HAProxy-2.3 and recompile it:

```diff
diff --git a/include/haproxy/connection.h b/include/haproxy/connection.h
index 49f5d3f0f..c42ca17e6 100644
--- a/include/haproxy/connection.h
+++ b/include/haproxy/connection.h
@@ -271,7 +271,6 @@ static inline void cs_close(struct conn_stream *cs)
 {
        cs_shutw(cs, CS_SHW_SILENT);
        cs_shutr(cs, CS_SHR_RESET);
-       cs->flags = CS_FL_NONE;
 }
```
I'm unable to reproduce the bug. But, I can imagine why it happens by reading the code. It is a annoying because we will have to emit new 2.4/2.3/2.2 releases once fixed. So, first, I want to be sure the bug is really fixed with this small patch. I may have missed something.

**Comment by wtarreau** [comment]
I tried hard even with a slow client etc and couldn't manage to do it either, thus a test would be welcome.

**Comment by bdentino** [comment]
@capflam Would it be possible to provide an alpine-based docker image with this patch applied? Or at least point me to some instructions to create it? I would be happy to test this in our environment but the reality is that I have very limited free time and I will be much more likely to get to it sooner if it doesn't involve setting up a dev environment and creating a custom build.

**Comment by hyvs** [comment]
We notice same regression on debian package `2.2.18-1~bpo10+1`. Reverted to `2.2.17-1~bpo10+1` fixed the issue.

The problem appears randomly and seems to happen only on chuncked HTTP response.

Client (curl) error on truncated response : 
```
* HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
* stopped the pause stream!
* Connection #0 to host www.*****.com left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

No error are reported on server side.

**Comment by wtarreau** [comment]
This one is interesting because H2 works differently and does not yet contain the equivalent fix that was suspected to cause trouble to HTTP/1.

@hyvs is this something you can reliably reproduce ? If so I would appreciate it if you could enable traces in H2 so that we can see the sequence that leads to this. If your machine is in production that will be extremely verbose and it will be difficult to spot the relevant parts. If you can reproduce it on an isolated instance, then it might be worth testing:
```
$ socat - /path/to/stats-socket <<< "trace h2 sink buf0; trace h2 level developer; trace h2 verbosity complete; trace h2 start now"
... perform your test using curl ...
$ socat - /path/to/stats-socket <<< "show events buf0; trace 0" > /path/to/log-file.txt
```
And there we're interested by socat's output from `log-file.txt`. Just have a quick check that it doesn't disclose sensitive information (it should not but better check before than too late).

**Comment by hyvs** [comment]
My previous message maybe misleading you, H2 error is shown by CURL because we have CloudFlare in front of our infrastructure. 

[Client] -- http/2 --> [ CloudFlare ] -- http/1.1 --> [origin server (haproxy 2.2.18-1~bpo10+1)]

I guess, issue happens on 1.1 connection and break http/2 front connection. 

I can force http/1.1 on CURL, and prompted error becomes:
```
transfer closed with outstanding read data remaining
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (18) transfer closed with outstanding read data remaining
```

Say me if you still need debug traces, I can try to reproduce it on our testing infrastructure without production traffic.

**Comment by wtarreau** [comment]
Ah indeed, thanks for clarifying that point. In this case the trace could be useful in H1 (replace "h2" with "h1" in the commands). But only if you manage to more or less isolate your machine, otherwise all traces will be interleaved and might be hard to analyse.

**Comment by wtarreau** [comment]
By the way, in this case Christopher's patch above becomes relevant again. Do you think you can apply it and rebuild ?

**Comment by hyvs** [comment]
CURL request: 
```
curl 'https://haproxy-issue-1450.***.com/wp-admin/load-styles.php?c=1&dir=ltr&load%5Bchunk_0%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,wp-pointer,widgets&load%5Bchunk_1%5D=,site-icon,l10n,buttons,wp-auth-check,wp-jquery-ui-dialog,media-views&ver=5.8.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0' -H 'Accept: text/css,*/*;q=0.1' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: ******' -H 'Sec-Fetch-Dest: style' -H 'Sec-Fetch-Mode: no-cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers' --ipv4 --http1.1 -vvv  -k
*   Trying 104.***.***.***...
* TCP_NODELAY set
* Connected to haproxy-issue-1450.***.com (104.***.***.***) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jul 11 00:00:00 2021 GMT
*  expire date: Jul 10 23:59:59 2022 GMT
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
> GET /wp-admin/load-styles.php?c=1&dir=ltr&load%5Bchunk_0%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,wp-pointer,widgets&load%5Bchunk_1%5D=,site-icon,l10n,buttons,wp-auth-check,wp-jquery-ui-dialog,media-views&ver=5.8.2 HTTP/1.1
> Host: haproxy-issue-1450.***.com
> Accept-Encoding: deflate, gzip
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0
> Accept: text/css,*/*;q=0.1
> Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
> DNT: 1
> Connection: keep-alive
> Cookie: *****
> Sec-Fetch-Dest: style
> Sec-Fetch-Mode: no-cors
> Sec-Fetch-Site: same-origin
> Pragma: no-cache
> Cache-Control: no-cache
> TE: trailers
>
< HTTP/1.1 200 OK
< Date: Fri, 12 Nov 2021 15:30:58 GMT
< Content-Type: text/css; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< vary: Accept-Encoding
< expires: Sat, 12 Nov 2022 15:30:58 GMT
< cache-control: public, max-age=31536000
< content-encoding: gzip
< strict-transport-security: max-age=2592000; preload
< CF-Cache-Status: DYNAMIC
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=pnVWNJuNWSAp9DUy25vM03l3giqa9ULeQlUY0uV%2F2zIA3qlnBDwj5LPkb95lskW%2F2AxO3ILSmUc7BS5iTtRnY27IZXMViVEF4ri%2FImCpeNlOVYpqqJ%2FavfjGuS2D3Hs%2Fvtwucv9%2BjwrYbHkN"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< X-Content-Type-Options: nosniff
< Server: cloudflare
< CF-RAY: 6ad0cdfc6eaa4ed3-FRA
<
/*! This file is auto-generated */
```

Haproxy traces:
https://gist.github.com/hyvs/73144c292ff362ee5d1aa4b90638be57

Yes, if needed, I can try Christopher patch next week.

**Comment by wtarreau** [comment]
Excellent, thank you! That's a side effect of the "option httpclose" that you're having in your config. I could now reproduce it, but only between two different machines and with a bandwidth-limited link. But what matters is that I can now do it!

**Comment by wtarreau** [comment]
And the sad news is that Christopher's fix doesn't fix it :-(

**Comment by wtarreau** [comment]
So what I'm seeing for now:
- 2.2.18: with/without patch: occasionally truncated responses detected by curl when retreieving a 10MB file over a 100 Mbps link over SSL
- 2.3.15: truncation sometimes as well; none in 2.3.14
- 2.4.7/2.4.8: no truncation at different sizes, with nor without the patch, however I'm seeing the occasional "CR <BADREQ>" that I thought we got rid of, when the TLS stack reports an error after the shutdown that is transmitted upstream to the mux.
- 2.5-dev: I occasionally see the CR,<BADREQ> one but much less often than in 2.4.

I could bisect it on 2.3 and it's indeed caused by the backport of that one: a85c522d4 ("BUG/MINOR: mux-h1: Save shutdown mode if the shutdown is delayed").

Thus it seems that there's something else missing from 2.3 and older in the shutdown part that was revealed by this one. At this point I'll wait for Christopher to be back on monday so that we analyse all this calmly.

Many thanks for your trace, it was extremely useful. In the mean time if you need to upgrade you can still disable "option httpclose" (and usually it will result in less CPU usage for you). Otherwise better wait for more news once we figure what the root cause is. Have a nice week-end!

**Comment by wtarreau** [comment]
For the record, here's the sequence when it works fine (14=frontend socket, 15=backend socket). h1_shutw_conn() is called after the last block is sent. A TLS shutdown is sent followed by a shutdown(). The later shutdown has no effect. Please note that we close a first time in normal mode and a second time in silent mode, thus we already damage that connstream. After everything is done we shutdown yet another time inside the cs_close() call.

```
17:37:00.929949 sendto(14, "\27\3\3\10K\266[1c\271{\260\346\367\311\222\25\213\303\320W\341\206L8W<P?\376\334\4\342.\347\177R<\270},\263\10Uo?\213\312\371\354\341FO\361\211\23@7\200\315\222\200\233\232\243\334\251\231\255|\255F\356\263\352k\227\303\203I\227\327=\266=A\323\342\346\237\356& \360\220Dv\266\234\374\342\361\26\34eq\2003\356\204\236E\5ki\202\260%\320P\177e<8\2\200\267\354\201^\211\7(\v\233c\330\243\266\350\275\261p4Z\355\257\302\377\327\376'\334H\224t o\374\271\22\2628\260\305\26\357\6\371\306(>\260\331\270\4\307\21\264\34\377\274#_\330\321{|Z\25Uh\201o\r\364\232\251\217\31"..., 2128, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 2128
17:37:00.929977 write(1, "h1_shutw_conn conn=0x23f6300 flg=0x80001300\n", 44h1_shutw_conn conn=0x23f6300 flg=0x80001300) = 44
17:37:00.929993 sendto(14, "\25\3\3\0\32\266[1c\271{\260\347Xt\264\37e\377\351\213\314\376\266\236\23\366\352\1\312\340", 31, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 31
17:37:00.930011 shutdown(14, SHUT_WR)   = 0
17:37:00.930024 write(1, "cs_shutw conn=0x23f6300 mode=0 csflg=0xc040\n", 44cs_shutw conn=0x23f6300 mode=0 csflg=0xc040) = 44
17:37:00.930049 write(1, "cs_close conn=0x23f6300 before csflg=0xc040\n", 44cs_close conn=0x23f6300 before csflg=0xc040) = 44
17:37:00.930061 write(1, "cs_shutw conn=0x23f6300 mode=1 csflg=0xc0c0\n", 44cs_shutw conn=0x23f6300 mode=1 csflg=0xc0c0) = 44
17:37:00.930072 write(1, "cs_shutr conn=0x23f6300 mode=1 csflg=0xc0e0\n", 44cs_shutr conn=0x23f6300 mode=1 csflg=0xc0e0) = 44
17:37:00.930084 write(1, "cs_close after: conn=0x23f6300 csflg=0xc0e0\n", 44cs_close after: conn=0x23f6300 csflg=0xc0e0) = 44
17:37:00.930121 getpid()                = 14144
17:37:00.930132 getpid()                = 14144
17:37:00.930159 ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
17:37:00.930180 writev(1, [{iov_base="<134>", iov_len=5}, {iov_base="Nov 12 17:37:00 ", iov_len=16}, {iov_base="haproxy", iov_len=7}, {iov_base="[", iov_len=1}, {iov_base="14144", iov_len=5}, {iov_base="]", iov_len=1}, {iov_base=": ", iov_len=2}, {iov_base="192.168.0.209:54587 [12/Nov/2021:17:37:00.537] recv~ recv/s1 0/0/1/0/392 200 1048724 - - ---- 1/1/0/0/0 0/0 \"GET /?s=1m HTTP/1.1\"", iov_len=129}, {iov_base="\n", iov_len=1}], 9<134>Nov 12 17:37:00 haproxy[14144]: 192.168.0.209:54587 [12/Nov/2021:17:37:00.537] recv~ recv/s1 0/0/1/0/392 200 1048724 - - ---- 1/1/0/0/0 0/0 "GET /?s=1m HTTP/1.1") = 167
17:37:00.930232 write(1, "cs_close conn=0x23f6300 before csflg=0xc0e0\n", 44cs_close conn=0x23f6300 before csflg=0xc0e0) = 44
17:37:00.930246 write(1, "cs_shutw conn=0x23f6300 mode=1 csflg=0xc0e0\n", 44cs_shutw conn=0x23f6300 mode=1 csflg=0xc0e0) = 44
17:37:00.930280 write(1, "cs_shutr conn=0x23f6300 mode=1 csflg=0xc0e0\n", 44cs_shutr conn=0x23f6300 mode=1 csflg=0xc0e0) = 44
17:37:00.930292 write(1, "cs_close after: conn=0x23f6300 csflg=0xc0e0\n", 44cs_close after: conn=0x23f6300 csflg=0xc0e0) = 44
17:37:00.930307 close(15)               = 0
17:37:00.930370 close(14)               = 0
```

When it fails, the h1_shutw_conn() is called very late at the end, after cs_close(), which had already damaged the conn_stream with its silent close:

```
17:41:27.960138 write(1, "cs_shutw conn=0x13d4300 mode=0 csflg=0xc040\n", 44cs_shutw conn=0x13d4300 mode=0 csflg=0xc040) = 44
17:41:27.960152 write(1, "cs_close conn=0x13d4300 before csflg=0xc040\n", 44cs_close conn=0x13d4300 before csflg=0xc040) = 44
17:41:27.960196 write(1, "cs_shutw conn=0x13d4300 mode=1 csflg=0xc0c0\n", 44cs_shutw conn=0x13d4300 mode=1 csflg=0xc0c0) = 44
17:41:27.960212 write(1, "cs_shutr conn=0x13d4300 mode=1 csflg=0xc0e0\n", 44cs_shutr conn=0x13d4300 mode=1 csflg=0xc0e0) = 44
17:41:27.960224 write(1, "cs_close after: conn=0x13d4300 csflg=0xc0e0\n", 44cs_close after: conn=0x13d4300 csflg=0xc0e0) = 44
17:41:27.960253 getpid()                = 14161
17:41:27.960262 getpid()                = 14161
17:41:27.960297 ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
17:41:27.960317 writev(1, [{iov_base="<134>", iov_len=5}, {iov_base="Nov 12 17:41:27 ", iov_len=16}, {iov_base="haproxy", iov_len=7}, {iov_base="[", iov_len=1}, {iov_base="14161", iov_len=5}, {iov_base="]", iov_len=1}, {iov_base=": ", iov_len=2}, {iov_base="192.168.0.209:54588 [12/Nov/2021:17:41:27.596] recv~ recv/s1 0/0/1/0/363 200 1048724 - - ---- 1/1/0/0/0 0/0 \"GET /?s=1m HTTP/1.1\"", iov_len=129}, {iov_base="\n", iov_len=1}], 9<134>Nov 12 17:41:27 haproxy[14161]: 192.168.0.209:54588 [12/Nov/2021:17:41:27.596] recv~ recv/s1 0/0/1/0/363 200 1048724 - - ---- 1/1/0/0/0 0/0 "GET /?s=1m HTTP/1.1") = 167
17:41:27.960368 write(1, "cs_close conn=0x13d4300 before csflg=0xc0e0\n", 44cs_close conn=0x13d4300 before csflg=0xc0e0) = 44
17:41:27.960381 write(1, "cs_shutw conn=0x13d4300 mode=1 csflg=0xc0e0\n", 44cs_shutw conn=0x13d4300 mode=1 csflg=0xc0e0) = 44
17:41:27.960396 write(1, "cs_shutr conn=0x13d4300 mode=1 csflg=0xc0e0\n", 44cs_shutr conn=0x13d4300 mode=1 csflg=0xc0e0) = 44
17:41:27.960408 write(1, "cs_close after: conn=0x13d4300 csflg=0xc0e0\n", 44cs_close after: conn=0x13d4300 csflg=0xc0e0) = 44
17:41:27.960426 close(15)               = 0
17:41:27.960506 write(1, "h1_shutw_conn conn=0x13d4300 flg=0x80001300\n", 44h1_shutw_conn conn=0x13d4300 flg=0x80001300) = 44
```

**Comment by wtarreau** [comment]
The attached patch fixes it for me on both 2.3 and 2.2. It seems to me that all versions ought to have it but I'd first carefully reread the commit patches to understand why it was not done, as we apparently preferred to rely on the mux function's idempotence by then, when the connection attachment was converted to conn_streams. Maybe it was an early design mistake, maybe not :-/
[conn.diff.txt](https://github.com/haproxy/haproxy/files/7529160/conn.diff.txt)

**Comment by wtarreau** [comment]
Regarding the `CR <BADREQ>` in 2.4+, that appeared with this commit : c4bfa59f1 ("MAJOR: mux-h1: Create the client stream as later as possible"). Thus I think the mux might be trying to perform an extra read after the end of the req/resp and creates a stream where it could avoid it.

**Comment by wtarreau** [comment]
I fixed it in 2.5-dev14, and the fix will flow down as far as 2.2. If you could give the patch above a test before I would appreciate it. Thanks!

**Comment by hyvs** [comment]
@wtarreau I try your patch (https://github.com/haproxy/haproxy/files/7529160/conn.diff.txt) on haproxy-2.2.18 ; sadly I still receive truncated responses.

Haproxy traces with your patch : https://gist.github.com/hyvs/782bcb9bbc24ac822a8c43fa3fa565b7

Haproxy configs : https://gist.github.com/hyvs/07692025760ae62cc3092c1a84970860

My build process:
```
wget http://www.haproxy.org/download/2.2/src/haproxy-2.2.18.tar.gz

git apply 8c13a92da036b99bdff903f40b24a6d37bb9d781.patch

make USE_NS=1 \
    USE_TFO=1 \
    USE_OPENSSL=1 \
    USE_ZLIB=1 \
    USE_LUA=1 \
    USE_PCRE=1 \
    USE_SYSTEMD=1 \
    USE_LIBCRYPT=1 \
    USE_THREAD=1 \
    TARGET=linux-glibc

make PREFIX=/opt/haproxy-2.2.18 install
```

**Comment by capflam** [comment]
I found a typo in `src/mux_h1.c`, introduced in the 2.3.15 and backported to the 2.2.18. Could you try with this additional patch ?

```diff
diff --git a/src/mux_h1.c b/src/mux_h1.c
index 095f5f1005..18048c21d0 100644
--- a/src/mux_h1.c
+++ b/src/mux_h1.c
@@ -42,10 +42,10 @@
 #define H1C_F_IN_ALLOC       0x00000010 /* mux is blocked on lack of input buffer */
 #define H1C_F_IN_FULL        0x00000020 /* mux is blocked on input buffer full */
 #define H1C_F_IN_BUSY        0x00000040 /* mux is blocked on input waiting the other side */
-/* 0x00000080 - 0x000002000 unused */
+/* 0x00000080 unused */
 
-#define H1C_F_ST_SILENT_SHUT 0x00004000 /* silent (or dirty) shutdown must be performed */
-/* 0x000008000 unused */
+#define H1C_F_ST_SILENT_SHUT 0x00000100 /* silent (or dirty) shutdown must be performed */
+/* 0x000000200 .. 0x000008000 unused */
 
 /* Flags indicating the connection state */
 #define H1C_F_CS_ERROR       0x00001000 /* connection must be closed ASAP because an error occurred */
```

**Comment by hyvs** [comment]
@capflam your additional patch seems to fix the issue.

**Comment by capflam** [comment]
Cool, thanks !
