### ISSUE TITLE
Old worker does not stop with seemingly no valid sessions

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1891]
### Detailed Description of the Problem

On one HAProxy host I'm seeing an old worker with an open frontend connection, without any backend connections that I expect to already be closed:

```
$ nc -U /run/haproxy-master.sock
prompt
master> show proc
#<PID>          <type>          <reloads>       <uptime>        <version>      
7809            master          83 [failed: 0]  4d17h32m47s     2.6.6-1~bpo10+1
# workers
27690           worker          0               0d00h24m09s     2.6.6-1~bpo10+1
# old workers
7286            worker          2               0d05h41m31s     2.6.6-1~bpo10+1
# programs
```

```
master> @!7286
7286> show sess
0x7f056c3f7510: proto=sockpair src=unix:2 fe=GLOBAL be=<NONE> srv=<none> ts=00 epoch=0 age=0s calls=1 rate=0 cpu=0 lat=0 rq[f=c08000h,i=0,an=00h,rx=,wx=,ax=] rp[f=80008000h,i=0,an=00h,rx=,wx=,ax=] scf=[8,200h,fd=9] scb=[8,1h,fd=-1] exp= rc=0 c_exp=
```

```
7286> show fd
      5 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x2 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
      6 : st=0x020121(Cl heopI W:sRa R:srA) tmask=0xff umask=0x0 owner=0x559fad731070 iocb=0x559faa1d1dd0(mworker_accept_wrapper)
      7 : st=0x000022(cl heopi W:sRa R:sRa) tmask=0x2 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
      9 : st=0x000021(cl heopi W:sRa R:srA) tmask=0x10 umask=0x10 owner=0x7f055480a4e0 iocb=0x559faa1d1780(sock_conn_iocb) back=0 cflg=0x00000300 fam=unix fe=GLOBAL mux=PASS ctx=0x7f05746a6650 xprt=RAW
     11 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x4 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     12 : st=0x000022(cl heopi W:sRa R:sRa) tmask=0x4 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     18 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x8 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     19 : st=0x000022(cl heopi W:sRa R:sRa) tmask=0x8 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     21 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x20 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     22 : st=0x000022(cl heopi W:sRa R:sRa) tmask=0x20 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     24 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x40 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     25 : st=0x000022(cl heopi W:sRa R:sRa) tmask=0x40 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     27 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x10 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     28 : st=0x000022(cl heopi W:sRa R:sRa) tmask=0x10 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     30 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x80 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     31 : st=0x000022(cl heopi W:sRa R:sRa) tmask=0x80 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     33 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x1 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     34 : st=0x000022(cl heopi W:sRa R:sRa) tmask=0x1 umask=0x0 owner=0x559faa1d9090 iocb=0x559faa1d9090(poller_pipe_io_handler)
     35 : st=0x000121(cl heopI W:sRa R:srA) tmask=0xffffffffffffffff umask=0xffffffffffffff00 owner=0x559fab26c6a0 iocb=0x559faa201a20(dgram_fd_handler)
    795 : st=0x000121(cl heopI W:sRa R:srA) tmask=0x1 umask=0x0 owner=0x559fada73b30 iocb=0x559faa1d1780(sock_conn_iocb) back=0 cflg=0xa0000300 fam=ipv6 lport=443 rport=58152 fe=https mux=H2 ctx=0x559fae780930 h2c.st0=FRH .err=0 .maxid=59 .lastid=2147483647 .flg=0x11200 .nbst=0 .nbcs=0 .fctl_cnt=0 .send_cnt=0 .tree_cnt=0 .orph_cnt=0 .sub=1 .dsi=0 .dbuf=0@(nil)+0/0 .msi=-1 .mbuf=[6..6|32],h=[0@(nil)+0/0],t=[0@(nil)+0/0] xprt=SSL xprt_ctx=0x7f0554703a90 xctx.st=0 .xprt=RAW .wait.ev=1 .subs=0x559fae780e38(ev=1 tl=0x559fae411900 tl.calls=853 tl.ctx=0x559fae780930 tl.fct=h2_io_cb) .sent_early=0 .early_in=0
```

```
7286> show info
Name: HAProxy
Version: 2.6.6-1~bpo10+1
Release_date: 2022/09/22
Nbthread: 8
Nbproc: 1
Process_num: 1
Pid: 7286
Uptime: 0d 5h41m52s
Uptime_sec: 20512
Memmax_MB: 0
PoolAlloc_MB: 4
PoolUsed_MB: 4
PoolFailed: 0
Ulimit-n: 20429
Maxsock: 20429
Maxconn: 10000
Hard_maxconn: 10000
CurrConns: 1
CumConns: *snip*
CumReq: *snip*
MaxSslConns: 0
CurrSslConns: 1
CumSslConns: *snip*
Maxpipes: 0
PipesUsed: 0
PipesFree: 0
ConnRate: 0
ConnRateLimit: 0
MaxConnRate: *snip*
SessRate: 0
SessRateLimit: 0
MaxSessRate: *snip*
SslRate: 0
SslRateLimit: 0
MaxSslRate: 2163
SslFrontendKeyRate: 0
SslFrontendMaxKeyRate: *snip*
SslFrontendSessionReuse_pct: 0
SslBackendKeyRate: *snip*
SslBackendMaxKeyRate: *snip*
SslCacheLookups: *snip*
SslCacheMisses: *snip*
CompressBpsIn: 0
CompressBpsOut: 0
CompressBpsRateLim: 0
Tasks: 757
Run_queue: 0
Idle_pct: 97
node: *snip*
Stopping: 1
Jobs: 4
Unstoppable Jobs: 1
Listeners: 1
ActivePeers: 0
ConnectedPeers: 0
DroppedLogs: 2320
BusyPolling: 0
FailedResolutions: 0
TotalBytesOut: *snip*
TotalSplicdedBytesOut: 0
BytesOutRate: 55264
DebugCommandsIssued: 0
CumRecvLogs: 0
Build info: 2.6.6-1~bpo10+1
Memmax_bytes: 0
PoolAlloc_bytes: 4220392
PoolUsed_bytes: 4220392
Start_time_sec: 1665457760
Tainted: 0
```

I can extract additional information from the process, it is still alive.

### Expected Behavior

The worker exits, because no in-flight requests need to be handled.

### Steps to Reproduce the Behavior

Unclear, this was a random find.

### What is your configuration?

```haproxy
# Additional information available on request: We use upstream Proxy Protocol, Peers, Request IDs, …

global
	log stdout format short daemon
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
	set-dumpable

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base "$CONFIG_DIRECTORY"/tls

	tune.ssl.default-dh-param 2048

	# TLS 1.2-
	ssl-default-bind-ciphers      ECDHE+CHACHA20:ECDHE+AES128:ECDHE+AES256:!MD5
	# TLS 1.3+
	ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
	# Require TLS 1.2 or higher
	ssl-default-bind-options      ssl-min-ver TLSv1.2 prefer-client-ciphers

	maxconn 10000

	# 12 hours
	hard-stop-after 43200s

defaults
	timeout connect 5s
	timeout client  50s
	timeout server  130s
	timeout http-request 5s
	timeout check 1s

	unique-id-format %{+X}o\ %[hostname,field(1,.),upper]-%Ts%rt

	default-server init-addr libc,none resolvers unbound

resolvers unbound
	nameserver unbound 127.0.0.1:53
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.6-1~bpo10+1 2022/09/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.6.html
Running on: Linux 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.6.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by capflam** [comment]
Indeed. Here the GOAWAY message was sent because of the reload. There is no more stream. I guess HAProxy is waiting  for the client shutdown. I don't know why there is no timeout here. I will check with Willy.

**Comment by TimWolla** [comment]
Just to let you know: The old worker now died, likely due to the hard-stop-after I had to set to work around #1874. So I'll not be able to extract further information from the process.

**Comment by capflam** [comment]
Well, I may miss something but by reading the code, I don't see how it is possible. An idle frontend connection must hit the client timeout (or client-fin timeout). So I suspect there is a memory corruption somewhere. It may be a side effect of #1862. It's a little thin, but that's all i see at the moment.

**Comment by mrngm** [comment]
I'm not entirely sure if the issue we're experiencing can be compared to this one, but we do see a lot of old workers active, most of them with fds in CLOSE-WAIT state. Since about 2 months ago, available memory on this machine started to decrease slowly from about 3.2GB free to currently 1GB free. Currently, we have 1 master process, 1 worker, and 89 'old workers', with the oldest having an uptime of 236d07h34m32s.

Apart from starting with `haproxy -vv`, I can either post more details here, or open a new issue. What would be the preferred approach here?

```
# haproxy -vv
HA-Proxy version 2.2.22-1ppa1~focal 2022/03/15 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.22.html
Running on: Linux 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-SZva2Z/haproxy-2.2.22=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

**Comment by TimWolla** [comment]
> Apart from starting with `haproxy -vv`, I can either post more details here, or open a new issue. What would be the preferred approach here?

@mrngm First thing I would recommend you upgrading to the latest 2.2.x (which is currently 2.2.25). Perhaps you're hitting a bug that is already fixed. I would recommend you doing a clean restart of HAProxy after the upgrade to ensure the old workers go away.

**Comment by mrngm** [comment]
> @mrngm First thing I would recommend you upgrading to the latest 2.2.x (which is currently 2.2.25). Perhaps you're hitting a bug that is already fixed. I would recommend you doing a clean restart of HAProxy after the upgrade to ensure the old workers go away.

Thanks for the answer. We'll have to plan this upgrade on a rather quiet moment, as we do not have the flexibility to redirect traffic to another instance. Should the problem persist after the upgrade to 2.2.25, I suppose the best way forward then is to open a new issue?

**Comment by TimWolla** [comment]
> We'll have to plan this upgrade on a rather quiet moment, as we do not have the flexibility to redirect traffic to another instance.

FWIW: If you opt to *not restart* HAProxy, then the upgrade should be seamless without any dropped traffic. Even if the old workers do not go away then, the new ones should (hopefully) do on a reload.

> Should the problem persist after the upgrade to 2.2.25, I suppose the best way forward then is to open a new issue?

Yes, I guess it's best to create a dedicated issue and cross-reference this one. It's not clear that you are hitting the same issue I am (or was).

**Comment by capflam** [comment]
@mrngm, to be the same bug, it must concern stalled H2 connection, without streams and no expiration timeout. Otherwise, it is probably something else. Just to know, do you use the resolvers ?

**Comment by mrngm** [comment]
> @mrngm, to be the same bug, it must concern stalled H2 connection, without streams and no expiration timeout. Otherwise, it is probably something else. Just to know, do you use the resolvers ?

@capflam We do not have the `resolvers` stanza in our configuration, if that is what you mean. We did manage to upgrade to 2.2.25 (`2.2.25-1ppa1~focal`) just last night with a full restart of the (virtual) server.

I have a `show sess all` and `show fd` from the oldest worker alive before the upgrade. In the output of the latter command, it shows `mux=H1` on the line containing `conn_fd_handler`, so I suppose this is indeed a different issue (but I can still share the full output, if that is necessary).

If the problem persists on 2.2.25, I'll open a fresh issue.

**Comment by TimWolla** [comment]
I'm currently seeing the same symptom with HAProxy 2.7.7:

```
$ nc -U /run/haproxy-master.sock
prompt
master> show proc
#<PID>          <type>          <reloads>       <uptime>        <version>      
*snip*
466183          worker          9               0d03h28m11s     2.7.7-1~bpo11+1
*snip*
```
```
master> @!466183
466183> show sess
0x55dec0113c50: proto=sockpair src=unix:2 fe=GLOBAL be=<NONE> srv=<none> ts=00 epoch=0 age=0s calls=1 rate=0 cpu=0 lat=0 rq[f=c08000h,i=0,an=00h,rx=,wx=,ax=] rp[f=80008000h,i=0,an=00h,rx=,wx=,ax=] scf=[8,200h,fd=15] scb=[8,1h,fd=-1] exp= rc=0 c_exp=
```
```
466183> show fd
      6 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x2 umask=0x0 prmsk=0x2 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
      7 : st=0x000022(cl heopi W:sRa R:sRa) ref=0 gid=1 tmask=0x2 umask=0x0 prmsk=0x0 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
      9 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x4 umask=0x0 prmsk=0x4 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     10 : st=0x000022(cl heopi W:sRa R:sRa) ref=0 gid=1 tmask=0x4 umask=0x0 prmsk=0x0 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     12 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x8 umask=0x0 prmsk=0x8 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     13 : st=0x020121(Cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0xff umask=0x0 prmsk=0xff pwmsk=0x0 owner=0x55debc47be30 iocb=0x55debab068c0(mworker_accept_wrapper)
     14 : st=0x000022(cl heopi W:sRa R:sRa) ref=0 gid=1 tmask=0x8 umask=0x0 prmsk=0x0 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     15 : st=0x000021(cl heopi W:sRa R:srA) ref=0 gid=1 tmask=0x80 umask=0x80 prmsk=0x0 pwmsk=0x0 owner=0x55debf962100 iocb=0x55debab06390(sock_conn_iocb) back=0 cflg=0x00000300 cerr=0 fam=unix fe=GLOBAL mux=PASS ctx=0x7fde20eb2e00 xprt=RAW
     22 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x20 umask=0x0 prmsk=0x20 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     23 : st=0x000022(cl heopi W:sRa R:sRa) ref=0 gid=1 tmask=0x20 umask=0x0 prmsk=0x0 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     25 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x40 umask=0x0 prmsk=0x40 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     26 : st=0x000022(cl heopi W:sRa R:sRa) ref=0 gid=1 tmask=0x40 umask=0x0 prmsk=0x0 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     28 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x10 umask=0x0 prmsk=0x10 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     29 : st=0x000022(cl heopi W:sRa R:sRa) ref=0 gid=1 tmask=0x10 umask=0x0 prmsk=0x0 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     31 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x80 umask=0x0 prmsk=0x80 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     32 : st=0x000022(cl heopi W:sRa R:sRa) ref=0 gid=1 tmask=0x80 umask=0x0 prmsk=0x0 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     34 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x1 umask=0x0 prmsk=0x1 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     35 : st=0x000022(cl heopi W:sRa R:sRa) ref=0 gid=1 tmask=0x1 umask=0x0 prmsk=0x0 pwmsk=0x0 owner=0x55debab0e080 iocb=0x55debab0e080(poller_pipe_io_handler)
     37 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0xff umask=0x0 prmsk=0xff pwmsk=0x0 owner=0x55debc486c60 iocb=0x55debab3ac30(dgram_fd_handler)
    331 : st=0x000121(cl heopI W:sRa R:srA) ref=0 gid=1 tmask=0x8 umask=0x0 prmsk=0x8 pwmsk=0x0 owner=0x7fde30e84800 iocb=0x55debab06390(sock_conn_iocb) back=0 cflg=0xa0000300 cerr=0 fam=ipv6 lport=443 rport=44098 fe=https mux=H2 ctx=0x7fde30eae910 h2c.st0=FRH .err=0 .maxid=141 .lastid=2147483647 .flg=0x11200 .nbst=0 .nbsc=0 .fctl_cnt=0 .send_cnt=0 .tree_cnt=0 .orph_cnt=0 .sub=1 .dsi=0 .dbuf=0@(nil)+0/0 .mbuf=[20..20|32],h=[0@(nil)+0/0],t=[0@(nil)+0/0] .task=0x7fde304fda90 .exp=40s xprt=SSL xprt_ctx=0x7fde401f3060 xctx.st=0 .err=0 .xprt=RAW .wait.ev=1 .subs=0x7fde30eaee08(ev=1 tl=0x7fde30e849d0 tl.calls=1112 tl.ctx=0x7fde30eae910 tl.fct=h2_io_cb) .sent_early=0 .early_in=0
```
```
466183> show info
Name: HAProxy
Version: 2.7.7-1~bpo11+1
Release_date: 2023/04/28
Nbthread: 8
Nbproc: 1
Process_num: 1
Pid: 466183
Uptime: 0d 3h28m28s
Uptime_sec: 12508
Memmax_MB: 0
PoolAlloc_MB: 3
PoolUsed_MB: 3
PoolFailed: 0
Ulimit-n: 20451
Maxsock: 20451
Maxconn: 10000
Hard_maxconn: 10000
CurrConns: 1
CumConns: *snip*
CumReq: *snip*
MaxSslConns: 0
CurrSslConns: 1
CumSslConns: *snip*
Maxpipes: 0
PipesUsed: 0
PipesFree: 0
ConnRate: 0
ConnRateLimit: 0
MaxConnRate: *snip*
SessRate: 0
SessRateLimit: 0
MaxSessRate: *snip*
SslRate: *snip*
SslRateLimit: *snip*
MaxSslRate: *snip*
SslFrontendKeyRate: *snip*
SslFrontendMaxKeyRate: *snip*
SslFrontendSessionReuse_pct: *snip*
SslBackendKeyRate: *snip*
SslBackendMaxKeyRate: *snip*
SslCacheLookups: *snip*
SslCacheMisses: *snip*
CompressBpsIn: 0
CompressBpsOut: 0
CompressBpsRateLim: 0
Tasks: 782
Run_queue: 0
Idle_pct: 100
node: *snip*
Stopping: 1
Jobs: 3
Unstoppable Jobs: 1
Listeners: 1
ActivePeers: 0
ConnectedPeers: 0
DroppedLogs: 5
BusyPolling: 0
FailedResolutions: 0
TotalBytesOut: *snip*
TotalSplicdedBytesOut: 0
BytesOutRate: 0
DebugCommandsIssued: 0
CumRecvLogs: 0
Build info: 2.7.7-1~bpo11+1
Memmax_bytes: 0
PoolAlloc_bytes: 4053344
PoolUsed_bytes: 4053344
Start_time_sec: 1683093630
Tainted: 0
```

The process will likely be alive for another 9 hours until it hard stops. If you need any additional info I can provide it until then.

**Comment by capflam** [comment]
Thanks @TimWolla. In your last `show fd` output, I can see the expiration is still set on the H2 connection (`.exp=40s`). It is a new hint that suggests the connection is still alive. My analysis is the client has ignored the GOAWAY frame.  For this point, I'm able to reproduce the issue with a client sending PING frames in loop. Not too often but just enough to refresh the connection timeout before its expiration. 

We've checked the code with @wtarreau. The `http-request/http-keep-alive` timeouts are ignored from the moment a GOAWAY frame was sent. It is a first issue. Then the function responsible to refresh the timeout must be reviewed to be handle configured timeouts in the right order and on more accurate conditions. @wtarreau is working on a patch.

**Comment by capflam** [comment]
I'm adding the "fixed" label because a fix was provided. We will wait a bit before backporting it to 2.6, to be sure. Thanks !

**Comment by capflam** [comment]
Now backported to 2.6. I'm closing the issue.
