### ISSUE TITLE
QUIC protocol error with Chrome-based browsers

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#2004]
### Detailed Description of the Problem

On our dev environment, where we have QUIC enabled, we regularly get images failing to be served on Chromium-based browsers, with the `net::ERR_QUIC_PROTOCOL_ERROR 200` error code.

This eventually makes the browser refuse to use QUIC with our origin for a while as well.

Obviously this isn't a lot of information to go off of, so I included some quic traces (see below).

### Expected Behavior

No error

### Steps to Reproduce the Behavior

Not entirely clear at this stage.

Our best reproducer so far is to load a page full of images (doesn't seem to happen regularly with plain HTML and other smaller payloads). Such a way we can reproduce it on our dev environment is as follows:
1. Start chromium forcing QUIC to the origin: `chromium-browser --enable-quic --origin-to-force-quic-on=sandbox.mangadex.dev:443`
1. Accessing a page with a lot of images, like https://sandbox.mangadex.dev/titles
2. Set the view mode to grid so larger (& thus bigger) thumbnails are loaded
![2023-01-18 10_50_19](https://user-images.githubusercontent.com/875533/213152658-067cd16c-0bef-4420-932b-443394896bbb.png)
3. Go to the next page until it happens (pagination at the bottom, usually I hit it after 1 or 2 pages only)

Note: if you try to repro, use the pagination for new images, rather than disabling the browser cache and refreshing the page, JS assets loading spam will get you rate-limited after a few refreshes otherwise due to a bug in our dev environment rate-limiting config.

### What is your configuration?

```haproxy
ring ring-shm-quic
  format timed
  maxlen 3072
  size 134217728 # 128MB
  backing-file /dev/shm/haproxy-quic

global
  ...

  expose-experimental-directives
  trace quic sink ring-shm-quic
  trace quic level developer
  trace quic start now

  tune.bufsize 32768

defaults defaults-base
  ...
  timeout client          5s
  timeout connect         3s

frontend mdex-public-direct from defaults-base
    bind 45.129.229.21:80 tfo
    bind 45.129.229.21:443 ssl strict-sni crt /etc/haproxy/ssl/mangadex.dev.pem alpn h2,http1.1 tfo allow-0rtt
    bind quic4@45.129.229.21:443 ssl strict-sni crt /etc/haproxy/ssl/mangadex.dev.pem alpn h3 allow-0rtt shards by-thread

default defaults-mangadex-uploads from defaults-base
    ...
    http-request normalize-uri fragment-strip
    http-request normalize-uri path-merge-slashes
    http-request normalize-uri path-strip-dotdot full
    http-request normalize-uri path-strip-dot
    http-request normalize-uri percent-decode-unreserved strict
    http-request normalize-uri percent-to-uppercase strict
    http-request normalize-uri query-sort-by-name

backend mdex_uploads_covers from defaults-mangadex-uploads
    server local-nginx unix@/nginx.sock check
    server mtc-xyz redacted:80 check slowstart 5s
    server-template image-origin-lb- 8 redacted:80 check resolvers xlbdns init-addr none backup
    server-template app-wrk-lb-      8 redacted:80 check resolvers xlbdns init-addr none backup
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8-dev1-86aac23+mangadex-4672057 2023-01-18T10:15+00:00 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -ggdb3 -gdwarf-4 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=5
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_STATIC_PCRE2=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_MEMORY_POOLS -DDEBUG_STRICT

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1s+quic-mangadex-4672057 18 Jan 2023
Running on OpenSSL version : OpenSSL 1.1.1s+quic-mangadex-4672057 18 Jan 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 14.0.6

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
n/a
```

### Additional Information

Attached is a QUIC developer trace around one such event

[haproxy-quic-protocol-error-1117.gz](https://github.com/haproxy/haproxy/files/10445324/haproxy-quic-protocol-error-1117.gz)

It *might* be loosely related to a backend exhibiting symptoms of https://github.com/haproxy/haproxy/issues/1992 . In this case, the images are proxy-cached by nginx from our prod, which is running 2.7.1 and thus affected by it (until a 2.7.2 bundling it is issued). Without forcing the origin, the browser will downgrade from QUIC to H2, and you'll get those instead of the QUIC errors. On one hand you could say we should try with prod on 2.8-dev + that fix, but on the other hand it's rather odd for haproxy to be affected like that by a faulty backend (even if it's nginx->haproxy in that case).

Though to be completely honest that one occasional quic error has been happening for a while, so it might be a coincidence and go way back.

Another interesting aspect is that the browser eventually retries the H3 request and gets a 206 back (from nginx's cache in such cases). Maybe ranges responses are somehow not very nicely handled. Hard to say.

**Comment by haproxyFred** [comment]
Hello, I had a look to your traces. First I would like to know if you stripped some information. The transport parameters (TP) traces are missing. I ask that because there are suspect trace for 0x78657805b410 QUIC connection (without TP dump). haproxy received the last 1RTT here:

**Comment by haproxyFred** [comment]
Hello,  error 200 QUIC error protocol looks like the h3 application error code H3_NO_ERROR meaning "no error".

About the traces, I would like to know if you stripped some information. The transport parameters (TP) traces are missing. I ask that because there are suspect trace for 0x78657805b410 QUIC connection (without TP dump). haproxy received the last 1RTT here without any remaining packet in flight:

<0>2023-01-18T11:17:11.617894+00:00 [02|quic|2|c_conn.c:2777] RX frame : qc@0x78657805b410 frm@0x78658de48e98 PADDING

Then after about 60s of inactivity it closes only the mux:

<0>2023-01-18T11:17:12.608935+00:00 [02|quic|5|prt_quic.c:26] quic_close(): entering : qc@0x78657805b410
<0>2023-01-18T11:17:12.608953+00:00 [02|quic|5|c_conn.c:1599] qc_check_close_on_released_mux(): entering : qc@0x78657805b410
<0>2023-01-18T11:17:12.608955+00:00 [02|quic|5|c_conn.c:1607] qc_check_close_on_released_mux(): leaving : qc@0x78657805b410
<0>2023-01-18T11:17:12.608957+00:00 [02|quic|5|prt_quic.c:39] quic_close(): leaving : qc@0x78657805b410

A few minutes later:

<0>2023-01-18T11:17:18.283501+00:00 [02|quic|5|c_conn.c:5801] retrieve_qc_conn_from_cid(): entering
<0>2023-01-18T11:17:18.283508+00:00 [02|quic|5|c_conn.c:5837] retrieve_qc_conn_from_cid(): leaving : qc@0x78657805b410 err_code=0x100

haproxy set its application error code to H3_NO_ERROR.

Then haproxy receives new STREAM frames. As the connection is not released contrary to the mux haproxy sends STOP_SENDING for STREAM it receives new data. Even for h3 Control Stream with 10 as ID which is a unidirectional stream open by the client if I remember well.

Chrome does not seems happy to receive such a STOP_SENDING for the h3 Control stream:

<0>2023-01-18T11:17:18.293377+00:00 [02|quic|2|c_conn.c:2777] RX frame : qc@0x78657805b410 frm@0x78658de48e98 CONNECTION_CLOSE_APP error_code=260 reason_phrase_len=47 reason_phrase: '156:STOP_SENDING received for QPACK send stream'

Error 260 is this one about the h3 RFC:

`H3_CLOSED_CRITICAL_STREAM (0x104):  A stream required by the HTTP/3
      connection was closed or reset.`

About h3 Control streams:

`
6.2.1 Control streams
The
   sender MUST NOT close the control stream, and the receiver MUST NOT
   request that the sender close the control stream.
`
I do not know if such an error may lead the client to never come back.

**Comment by haproxyFred** [comment]
To me we should at least modify our code to never send STOP_SENDING frames for h3 Control stream.

**Comment by Tristan971** [comment]
> About the traces, I would like to know if you stripped some information. The transport parameters (TP) traces are missing. I ask that because there are suspect trace for 0x78657805b410 QUIC connection (without TP dump).

Hmm unless haproxy sometimes spans traces over 2 lines (defeating the grep-ing) that shouldn't be the case; I generated the trace extract off the ring file like so: `haring -f haproxy-quic | grep 'T11:17' > haproxy-quic-protocol-error-1117` then gzipped that.

> To me we should at least modify our code to never send STOP_SENDING frames for h3 Control stream.

I can always try a patch w/ that change and see if that fixes it; since it's trivially reproducible on our dev environment in seconds that's not a problem

**Comment by Tristan971** [comment]
So, it does seem like some of the lines are not time-prefixed at times, which might be why you were surprised. Also I made sure to not close the browser (maybe that caused the client-initiated closes of the earlier traces) before copying the traces.

There should be 2 events in here, one around 09:26-09:27, and one at 09:29 (and maybe more events before, but I don't know for sure).

[haproxy-quic-protocol-error-0929.gz](https://github.com/haproxy/haproxy/files/10465047/haproxy-quic-protocol-error-0929.gz)

To make sure nothing was cut I didn't filter anything, so the traces start a bit earlier (but maybe there's other interesting things to find in there as well). Also this is in haring format (not sure what you call it), rather than post-haring+grep text.

**Comment by haproxyFred** [comment]
I have just pushed a fix here:
https://github.com/haproxytech/quic-dev/commit/d18025eeef03dd82d60860d60245c93dc4feadb7

**Comment by haproxyFred** [comment]
> So, it does seem like some of the lines are not time-prefixed at times, which might be why you were surprised. Also I made sure to not close the browser (maybe that caused the client-initiated closes of the earlier traces) before copying the traces.

Ah, yes TP are dumped with a  newline character between each of them. So, without timestamp.

**Comment by Tristan971** [comment]
> I have just pushed a fix here

Unfortunately still happens. Traces here: [haproxy-quic-protocol-error-1523.gz](https://github.com/haproxy/haproxy/files/10467593/haproxy-quic-protocol-error-1523.gz)

Maybe of interest, I notice that the log line for it (ie in haproxy logs) is output at the error level, despite being a 200 (ie the 7 red ones in the screenshot below; though Chrome reported 5 errors in this case). So it seems like HAProxy itself is aware of something going wrong.

![2023-01-20 15_28_47](https://user-images.githubusercontent.com/875533/213736473-9167cfde-b888-42e2-a067-9bd1d0f7b588.png)

**Comment by haproxyFred** [comment]
Il would be interesting to have the mux and h3 enabled.

**Comment by haproxyFred** [comment]
For the mux:

   trace qmux sink ring-shm-quic
   trace qmux level developer
   trace qmux start now

and h3:

    trace h3 sink ring-shm-quic
    trace h3 level developer
    trace h3 start now

**Comment by Tristan971** [comment]
I'll do that right now, should have the traces back shortly

**Comment by Tristan971** [comment]
Here you go: [haproxy-quic-protocol-error-1611.gz](https://github.com/haproxy/haproxy/files/10467992/haproxy-quic-protocol-error-1611.gz)

**Comment by Tristan971** [comment]
(also I cannot express how much more convenient having the trace directives in the global section is; it's a real blessing)

**Comment by haproxyFred** [comment]
No more STOP_SENDING frames are sent for h3 unidirectional streams. But this does not fix the issue.
But there are often STOP_SENDING, RESET_STREAM frames received from Chrome. Do not know why at this time.

**Comment by haproxyFred** [comment]
There are also data sent on unidirectional streams by Chrome, in the middle of the stream requests. Do not know what it is at this time. (id=6).

**Comment by a-denoyelle** [comment]
This is very difficult for us to understand the issue here as we have no way to reproduce it. Given your observation and the provided traces, it may be caused by our mux-quic sending unnecessary `RESET_STREAM`. Can you test the attached patch on top of the current master tip and tell us if this improves the situation ?

BTW, for `qmux` traces, can you set verbosity to `minimal` please ? This will ensure all info are provided.

[0001-MINOR-mux-quic-do-not-reset-stream-on-shutw.patch.txt](https://github.com/haproxy/haproxy/files/10479936/0001-MINOR-mux-quic-do-not-reset-stream-on-shutw.patch.txt)

**Comment by Tristan971** [comment]
Sure I will do that 👍 (As usual, I'm also happy to assist more directly if that might help you diagnose it somehow)

**Comment by a-denoyelle** [comment]
Sorry the patch was incomplete, here is an updated version.
[0001-MINOR-mux-quic-do-not-reset-stream-on-shutw.patch.txt](https://github.com/haproxy/haproxy/files/10479976/0001-MINOR-mux-quic-do-not-reset-stream-on-shutw.patch.txt)

**Comment by Tristan971** [comment]
> BTW, for qmux traces, can you set verbosity to minimal please ? This will ensure all info are provided.

@a-denoyelle I get `'trace': No such trace level` as an error when trying that

**Comment by a-denoyelle** [comment]
This is for the verbosity line not the level :
```
trace qmux sink stdout
trace qmux level developer
trace qmux verbosity minimal
trace qmux start now
```

FYI, level will filter events. Verbosity will extend the infos displayed on each line.

**Comment by Tristan971** [comment]
Right, my bad.

**Comment by Tristan971** [comment]
Alright so with your patch the frequency of the errors is much lower. From once every ~30 images to once every ~150 images.

However I do notice that it also introduces some kind of stalling. ie some requests get stalled for 4-5 seconds before going through (close to the same rate where they would error out before).

Either way, here's the traces: [haproxy-quic-202301231411.gz](https://github.com/haproxy/haproxy/files/10480474/haproxy-quic-202301231411.gz)

**Comment by Tristan971** [comment]
Funny thing looking at those traces. It seems like the few first lines of the file (until 2023-01-23T14:10:17.852537+00:00) are malformed (or haring output for them is anyway); not too sure why.

ie
```
$ haring -f haproxy-quic-202301231411
WARNING: header in file is 72 bytes long vs 64 expected!
550058290m<0>2023-01-23T14:11:28.600806+00:00 [02|quic|5|c_conn.c:7549] qc_notify_close(): enteri
 : qc@0x72b550058290l<0>2023-01-23T14:11:28.600808+00:00 [02|quic|5|c_conn.c:7565] qc_notify_close():
aving : qc@0x72b550058290o<0>2023-01-23T14:11:28.600811+00:00 [02|quic|5|c_conn.c:4978] quic_conn_re
ase(): entering : qc@0x72b550058290x<0>2023-01-23T14:11:28.600950+00:00 [02|quic|5|c_conn.c:4583] qu
_conn_enc_level_uninit(): entering : qc@0x72b550058290w<0>2023-01-23T14:11:28.600954+00:00 [02|qui
5|c_conn.c:4594] quic_conn_enc_level_uninit(): leaving : qc@0x72b550058290x<0>2023-01-23T14:11:28.600958+00:00 [02|quic|5|c
onn.c:4583] quic_conn_enc_level_uninit(): entering : qc@0x72b550058290w<0>2023-01-23T14:11:28.6009
+00:00 [02|quic|5|c_conn.c:4594] quic_conn_enc_l
el_uninit(): leaving : qc@0x72b550058290x<0>2023-01-23T14:11:28.600968+00:00 [02|quic|5|c_conn.c:4583] quic_conn_enc_
vel_uninit(): entering : qc@0x72b550058290w<0>2023-01-23T14:11:28.600971+00:00 [02|quic|5|c_conn.c:4
4
[...]
<0>2023-01-23T14:10:17.852537+00:00 [06|quic|5|c_conn.c:3072] qc_prep_app_pkts(): entering : qc@0x72b54c057060
<0>2023-01-23T14:10:17.852540+00:00 [06|quic|5|c_conn.c:3080] qc_prep_app_pkts(): in : qc@0x72b54c057060 qel=A state=HCF ack?0 cwnd=34524 ppif=21746 pif=21746 if=21746 pp=0 off=0
<0>2023-01-23T14:10:17.852541+00:00 [06|quic|5|c_conn.c:3131] qc_prep_app_pkts(): leaving : qc@0x72b54c057060
<0>2023-01-23T14:10:17.852542+00:00 [06|quic|5|c_conn.c:4115] qc_send_app_pkts(): leaving : qc@0x72b54c057060
<0>2023-01-23T14:10:17.852543+00:00 [06|quic|5|c_conn.c:4358] quic_conn_app_io_cb(): leaving : qc@0x72b54c057060
<0>2023-01-23T14:10:17.852545+00:00 [06|qmux|5|x_quic.c:2000] qc_io_cb(): entering : qcc=0x72b54c05cb50(F) qc=0x72b54c057060
<0>2023-01-23T14:10:17.852547+00:00 [06|qmux|5|x_quic.c:1726] qc_send(): entering : qcc=0x72b54c05cb50(F) qc=0x72b54c057060
<0>2023-01-23T14:10:17.852549+00:00 [06|qmux|5|x_quic.c:1311] qcs_xfer_data(): entering : qcc=0x72b54c05cb50(F) qc=0x72b54c057060 qcs=0x72b54c0896f0 .id=8 .st=HCR
```

**Comment by a-denoyelle** [comment]
> Alright so with your patch the frequency of the errors is much lower. From once every ~30 images to once every ~150 images.
> 
> However I do notice that it also introduces some kind of stalling. ie some requests get stalled for 4-5 seconds before going through (close to the same rate where they would error out before).
> 
> Either way, here's the traces: [haproxy-quic-202301231411.gz](https://github.com/haproxy/haproxy/files/10480474/haproxy-quic-202301231411.gz)

You mentionned that error rates decreases but still present. Does that still induce chrome to disable H3 ?

**Comment by a-denoyelle** [comment]
BTW, it could be useful to also activate `h3` traces to have the complete picture : 
```
trace h3 sink stdout
trace h3 level developer
trace h3 verbosity minimal
trace h3 start now
```

**Comment by Tristan971** [comment]
> Does that still induce chrome to disable H3 ?

@a-denoyelle Yes; you can see very clearly where the stalls happen (the batch of 10+ seconds images) and then the regression to H2

<details>
<summary>chrome network tab</summary>

![2023-01-24 14_23_16](https://user-images.githubusercontent.com/875533/214319986-b29f5110-fa78-4727-9a5c-b85cd80079a4.png)

![2023-01-24 14_23_28](https://user-images.githubusercontent.com/875533/214320002-8a2cd2f4-7592-4fa1-8844-1fad8a71800e.png)

</details>

> BTW, it could be useful to also activate `h3` traces to have the complete picture

Sure; for the record this is what I now have:
```
trace h3 sink ring-shm-quic
trace h3 level developer
trace h3 verbosity minimal
trace h3 start now
trace qmux sink ring-shm-quic
trace qmux level developer
trace qmux verbosity minimal
trace qmux start now
trace quic sink ring-shm-quic
trace quic level developer
trace quic start now
```

And here are the traces (session is from ~14:27 up to ~14:28): [haproxy-quic-202301241429.gz](https://github.com/haproxy/haproxy/files/10490855/haproxy-quic-202301241429.gz)

<details>
<summary>chrome network tab for the session with h3 verbosity</summary>

![2023-01-24 14_28_07](https://user-images.githubusercontent.com/875533/214321853-53903d03-beb1-4579-87d2-e07e9cc33075.png)

- First page loads all fine
- Second page has 3 stalled requests (each being a 10s stall => QUIC protocol error => chrome retry => then OK)

---

![2023-01-24 14_28_54](https://user-images.githubusercontent.com/875533/214322313-a535e56a-4846-4e33-9c7d-a929eff4b628.png)

- Third page has 10 stalled requests

---

![2023-01-24 14_29_01](https://user-images.githubusercontent.com/875533/214322575-175a7893-4fb1-4cf4-ae6e-af75b3e9c0ff.png)

- Fourth page all 32 requests get stalled

</details>

**Comment by Tristan971** [comment]
Also I'm not sure if this is of interest, but these are the CPU and UDP stats of the LB VM in question (tis purely for dev purposes, so it's the least busy thing imaginable, which shows as we have no UDP errors external to QUIC whatsoever nor any CPU/memory pressure)

![2023-01-24 15_06_49](https://user-images.githubusercontent.com/875533/214330683-a01b381f-f46c-4d57-9de9-df167d4338b6.png)

![2023-01-24 15_06_33](https://user-images.githubusercontent.com/875533/214330680-2fc9a252-3e2e-4fef-850a-ef1048df5ad5.png)

**Comment by a-denoyelle** [comment]
I did not have much time to work on this issue and it's not easy to understand chrome behavior as I failed in reproduce the issue locally with web services on my own.

Regarding the stalled requests, maybe this is caused due to a recent regression which prevent the H3 GOAWAY emission. I merged a fix for this in the master branch so you may perform a new test it with the previous patch applied.

If you still have issue, you can replace the patch by the new version provided in this comment. This is refined version with `RESET_STREAM` sent under certain condition instead of an empty STREAM with FIN set. This is experimental as it's not easy to test these conditions.
[0001-MINOR-mux-quic-do-not-reset-stream-on-shutw.patch.txt](https://github.com/haproxy/haproxy/files/10500669/0001-MINOR-mux-quic-do-not-reset-stream-on-shutw.patch.txt)

**Comment by Tristan971** [comment]
I will try and do that. If I somehow still reproduce it I’ll try to make a locally-usable reproducer

**Comment by a-denoyelle** [comment]
Well I messed up with my last commits so you will probably encounter a segfault on the latest master tip on connection init :/ I'm merging a fix ASAP.

**Comment by a-denoyelle** [comment]
I just pushed a fix it should be back to normal sorry for the inconvenient.

**Comment by Tristan971** [comment]
No worries, I hadn't had time to try it yet. I triggered new builds and will try in this order:
1. b4d119f0c75ce7c5a977ece18dc975e14f9b460c + the patch from https://github.com/haproxy/haproxy/issues/2004#issuecomment-1400312105
2. b4d119f0c75ce7c5a977ece18dc975e14f9b460c + the patch from https://github.com/haproxy/haproxy/issues/2004#issuecomment-1403780350
3. Try to come up with a local repro; it will probably be a bit messy but oh well

**Comment by Tristan971** [comment]
So option 1. failed, but I imagine this is just an interop bug with the old patch and the new tip of master, since it instantly failed with a QUIC handshake failure within the first 11 requests (for a class of small images that didn't fail before)

![2023-01-25 20_10_10](https://user-images.githubusercontent.com/875533/214678937-b2e93821-5007-45ef-890b-15cb077f6a73.png)

Traces here: [haproxy-quic-202301252007.gz](https://github.com/haproxy/haproxy/files/10503285/haproxy-quic-202301252007.gz)

**Comment by Tristan971** [comment]
Guess option 2. is a fail too. It started off really well, doing ~220 good fetches, then I had one or two stalls (but approximately 5s this time, compared to the previous 10s in https://github.com/haproxy/haproxy/issues/2004#issuecomment-1402050837 ), then the next page was handshake failures like option 1.

No idea exactly what causes this all but here's the stalls (going to the next page caused the same handshake failures as above, so not including a screenshot of that):
![2023-01-26 00_13_15](https://user-images.githubusercontent.com/875533/214723785-2d25d524-263f-45fd-a463-1578265b83d2.png)

And here's the traces: [haproxy-quic-202301260014.gz](https://github.com/haproxy/haproxy/files/10504781/haproxy-quic-202301260014.gz)

**Comment by a-denoyelle** [comment]
> So option 1. failed, but I imagine this is just an interop bug with the old patch and the new tip of master, since it instantly failed with a QUIC handshake failure within the first 11 requests (for a class of small images that didn't fail before)
> 
> ![2023-01-25 20_10_10](https://user-images.githubusercontent.com/875533/214678937-b2e93821-5007-45ef-890b-15cb077f6a73.png)
> 
> Traces here: [haproxy-quic-202301252007.gz](https://github.com/haproxy/haproxy/files/10503285/haproxy-quic-202301252007.

This result is really surprising to me. Chrome reports handshake failure but at first glance on the traces I saw two connection opened and each behaves normally with a lot of streams opened and closed over a period of time so this does not match with an handshake failure.

**Comment by Tristan971** [comment]
> at first glance on the traces I saw two connection opened and each behaves normally

haven’t checked those in-depth but it could be pre-update traces? I use a 128MB ring on there, so there’s often « old » traces at the top; only the 2 last minutes (when I poke around before making a copy of the ring) are really relevant 

if you said it while accounting for that then idk tho 😅

**Comment by Tristan971** [comment]
> [0001-MINOR-mux-quic-do-not-reset-stream-on-shutw.patch.txt](https://github.com/haproxy/haproxy/files/10500669/0001-MINOR-mux-quic-do-not-reset-stream-on-shutw.patch.txt)

Btw this patch doesn't build anymore with the current tip of 2.8-dev @a-denoyelle, see https://gitlab.com/mangadex-pub/haproxy/-/jobs/3731595725

```
  CC      src/quic_tls.o
src/h3.c:1674:13: warning: unused function 'h3_reset' [-Wunused-function]
static void h3_reset(struct qcs *qcs)
            ^
src/mux_quic.c:2475:21: fatal error: no member named 'reset' in 'struct qcc_app_ops'
                if (qcc->app_ops->reset)
                    ~~~~~~~~~~~~  ^
1 error generated.
make[2]: *** [Makefile:988: src/mux_quic.o] Error 1
```

**Comment by Tristan971** [comment]
In other news, running 2.8-dev ( d85227fca20a5c793857c1632283ef4a2120285a ) I get some QUIC protocol errors.

![2023-02-07 23_08_42](https://user-images.githubusercontent.com/875533/217387817-9cad0fe5-2edc-4050-a302-c7c96c81ce17.png)

But the good news is that I triggered those while setting up a reproducer for this issue as a whole

Here's the hacky configuration I came to https://github.com/Tristan971/haproxy-bug-repros/blob/issue-2004/haproxy.cfg

Unfortunately it's a bit tricky to even run correctly without accidentally having some H2 fallbacks triggering left and right...

You need to ensure the following:
1. You're using the local haproxy as an entrypoint (some /etc/hosts editing should do the trick)
2. You're forcing H3 etc on chrome (`chromium-browser --ignore-certificate-errors --enable-quic --origin-to-force-quic-on=localhost:443 --origin-to-force-quic-on=sandbox.mangadex.dev:443 --origin-to-force-quic-on=uploads.mangadex.dev:443` is my complete CLI command)
3. You can then access https://localhost which should load a proxied copy of our dev website

Probably you'll run into QUIC issues. But maybe not either. If not, then I have no good repro. I merely see it happen on 50% of chrome sessions; sometimes entirely breaking, sometimes images, sometimes working flawlessly. Hard to say for sure tbh...

**Comment by wtarreau** [comment]
Is this issue still relevant or should we close it ?

**Comment by Tristan971** [comment]
Unfortunately it still happens (albeit less often than before). We get a couple of end-user reports a day about it... Alas, I still have no idea of how to reproduce it and mostly hope it ends up "fixing itself" as a side-effect of something else...

**Comment by wtarreau** [comment]
OK thanks!

**Comment by wtarreau** [comment]
I'll mark it as "waiting for feedback" so that we think about having a look periodically and asking for any observed change.

**Comment by Tristan971** [comment]
Note that there was a person on the mailing list with an apparently reproducible test case of this just yesterday

**Comment by haproxyFred** [comment]
Indeed. Waiting for his answer.

**Comment by a-denoyelle** [comment]
For your information, I have pushed two fixes which should remove/reduce the number of spurrious RESET_STREAM frames. I hope it can improve the current issue.

**Comment by Tristan971** [comment]
Nice stuff, I'll give it a try soon-ish 👍

**Comment by Tristan971** [comment]
Got exciting news to share! My previous reproducer in our dev environment doesn't work anymore with these patches!

So while that might not have caught *all* cases, at least it seems to have caught a chunk of them indeed 🎉

**Comment by Tristan971** [comment]
The only caveat is that I don't have good options to monitor the results of these further (besides user complaints)... Wish I had setup a NEL collector but that's been on the very long todo list for 2 years now... 🥲

**Comment by a-denoyelle** [comment]
Indeed it's difficult to know for sure if a RESET_STREAM emitted by haproxy is justified or not. Anyway, above patches have been backported and released through 2.7.7 so I propose to close this issue for now :)
