### ISSUE TITLE
src/applet.c: null pointer dereference suspected by coverity

### ISSUE THREAD

**Issue by shipitsin-ilia** [haproxy/haproxy#2106]
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1508680:  Null pointer dereferences  (FORWARD_NULL)
/src/applet.c: 139 in applet_trace()
133                           appctx, appctx->t, tick_isset(appctx->t->expire) ? TICKS_TO_MS(appctx->t->expire - now_ms) : TICK_ETERNITY,
134                           appctx->state, appctx->st0, appctx->st1);
135     
136             if (!sc || src->verbosity == STRM_VERB_MINIMAL)
137                     return;
138     
>>>     CID 1508680:  Null pointer dereferences  (FORWARD_NULL)
>>>     Dereferencing null pointer "s".
139             chunk_appendf(&trace_buf, " - s=(%p,0x%08x,0x%x)", s, s->flags, s->conn_err_type);
140     
141             chunk_appendf(&trace_buf, " sc=(%p,%d,0x%08x,0x%x) sco=(%p,%d,0x%08x,0x%x) sc.exp(r,w)=(%d,%d) sc.exp(r,w)=(%d,%d)",
142                           sc, sc->state, sc->flags, sc->sedesc->flags,
143                           sco, sco->state, sco->flags, sco->sedesc->flags,
144                           tick_isset(sc_ep_rcv_ex(sc)) ? TICKS_TO_MS(sc_ep_rcv_ex(sc) - now_ms) : TICK_ETERNITY,
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by capflam** [comment]
This one is a false positive. `s` is defined if `sc` is defined. It means I should use `__sc_strm()` function to get the stream instead of the safe version. But I suspect Coverity will still report a possible null dereference.  I will push this fix and see if it is ok this way. Thanks.

**Comment by capflam** [comment]
I pushed the fix, we will see if Coverity still complains or not.

**Comment by shipitsin-ilia** [comment]
coverity runs daily. I'll reopen if issue is still there

thank you!

**Comment by chipitsine** [comment]
it's still detected by coverity

here's detailed report

```
630static int quic_bind_listener(struct listener *listener, char *errmsg, int errlen)
631{
632        const struct sockaddr_storage addr = listener->rx.addr;
633        int fd, err = ERR_NONE;
634        char *msg = NULL;
635
636        /* ensure we never return garbage */
   1. Condition errlen, taking true branch.
637        if (errlen)
638                *errmsg = 0;
639
   2. Condition listener->state != LI_ASSIGNED, taking false branch.
640        if (listener->state != LI_ASSIGNED)
641                return ERR_NONE; /* already bound */
642
   3. Condition !(listener->rx.flags & 1), taking false branch.
643        if (!(listener->rx.flags & RX_F_BOUND)) {
644                msg = "receiving socket not bound";
645                goto udp_return;
646        }
647
648        /* Set IP_PKTINFO to retrieve destination address on recv. */
649        fd = listener->rx.fd;
   4. Switch case value 2.
650        switch (addr.ss_family) {
651        case AF_INET:
652#if defined(IP_PKTINFO)
   CID 1498960 (#2 of 2): Unchecked return value from library (CHECKED_RETURN)5. check_return: Calling setsockopt(fd, IPPROTO_IP, 8, &one, 4U) without checking return value. This library function may fail and return an error code.
653                setsockopt(fd, IPPROTO_IP, IP_PKTINFO, &one, sizeof(one));
```

**Comment by capflam** [comment]
It seems to be the wrong report or the wrong issue :)

**Comment by ilia-shipitsin** [comment]
yeah, let's ignore it. I'll come back soon

**Comment by chipitsine** [comment]
here's detailed report

```
 94static void applet_trace(enum trace_level level, uint64_t mask, const struct trace_source *src,
 95                         const struct ist where, const struct ist func,
 96                         const void *a1, const void *a2, const void *a3, const void *a4)
 97{
 98        const struct appctx *appctx = a1;
 99        const struct stconn *sc = NULL, *sco = NULL;
100        const struct stream *s = NULL;
101        const struct channel *ic = NULL, *oc = NULL;
102
   1. Condition !appctx, taking false branch.
   2. Condition src->verbosity < 1, taking false branch.
103        if (!appctx || src->verbosity < STRM_VERB_CLEAN)
104                return;
105
106        sc = appctx_sc(appctx);
   3. Condition sc, taking true branch.
107        if (sc) {
108                s = __sc_strm(sc);
109                sco = sc_opposite(sc);
110                ic = sc_ic(sc);
111                oc = sc_oc(sc);
112        }
113
114        /* General info about the stream (htx/tcp, id...) */
   4. Condition s, taking false branch.
   5. var_compare_op: Comparing s to null implies that s might be null.
115        if (s)
116                chunk_appendf(&trace_buf, " : [%s,%s]",
117                              appctx->applet->name, ((s->flags & SF_HTX) ? "HTX" : "TCP"));
118        else
119                chunk_appendf(&trace_buf, " : [%s]", appctx->applet->name);
120
   6. Condition sc, taking true branch.
121        if (sc)
122                /* local and opposite stream connector state */
123                chunk_appendf(&trace_buf, " SC=(%s,%s)",
   7. Falling through to end of if statement.
124                              sc_state_str(sc->state), sc_state_str(sco->state));
125        else
126                /* local and opposite stream connector state */
127                chunk_appendf(&trace_buf, " SC=(none,none)");
128
   8. Condition src->verbosity == 1, taking false branch.
129        if (src->verbosity == STRM_VERB_CLEAN)
130                return;
131
   9. Condition tick_isset(appctx->t->expire), taking true branch.
132        chunk_appendf(&trace_buf, " appctx=%p .t=%p .t.exp=%d .state=%d .st0=%d .st1=%d",
133                      appctx, appctx->t, tick_isset(appctx->t->expire) ? TICKS_TO_MS(appctx->t->expire - now_ms) : TICK_ETERNITY,
134                      appctx->state, appctx->st0, appctx->st1);
135
   10. Condition !sc, taking false branch.
   11. Condition src->verbosity == 2, taking false branch.
136        if (!sc || src->verbosity == STRM_VERB_MINIMAL)
137                return;
138
   CID 1508680 (#1 of 1): Dereference after null check (FORWARD_NULL)12. var_deref_op: Dereferencing null pointer s.
139        chunk_appendf(&trace_buf, " - s=(%p,0x%08x,0x%x)", s, s->flags, s->conn_err_type);
```

**Comment by capflam** [comment]
There is nothing much I can do. It is just a false positive. The variable `s` cannot be NULL if `sc` is defined. `__sc_strm()` always return a valid pointer. So if `sc` is defined, `s` is defined too.

**Comment by chipitsine** [comment]
![image](https://user-images.githubusercontent.com/2217296/234628341-7880bae6-49ba-4bf3-b466-0c03b67a2a9e.png)
