### ISSUE TITLE
AWS-LC QUIC Interop C1/L1 tests fail very often  (s2n-quic client)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2663]
### Detailed Description of the Problem

running QUIC Interop against s2n-quic client:

FATAL: bug condition "first_pkt->type == QUIC_PACKET_TYPE_INITIAL && (first_pkt->flags & (1UL << 0)) && length < 1200" matched at src/quic_tx.c:163
  call trace(13):
  | 0x55f4ee4dcc02 [ba d9 00 00 00 48 8d 35]: main-0x195bf2
  | 0x55f4ee4e3112 [83 3d 2f 16 35 00 00 0f]: qc_send+0x11f3/0x1b5d
  | 0x55f4ee4e9ab4 [85 c0 0f 85 00 f6 ff ff]: quic_conn_io_cb+0xab1/0xf1c
  | 0x55f4ee6efa82 [48 c7 c0 f8 55 ff ff 64]: run_tasks_from_lists+0x173/0x9c2
  | 0x55f4ee6f05d3 [8b 7d a0 29 c7 85 ff 0f]: process_runnable_tasks+0x302/0x6e6
  | 0x55f4ee671bb7 [83 3d 86 72 44 00 01 0f]: run_poll_loop+0x6e/0x57b
  | 0x55f4ee672367 [48 8b 1d 22 d4 1d 00 48]: main-0x48d
  | 0x55f4ee6755e0 [b8 00 00 00 00 e8 08 61]: main+0x2dec/0x335d

### Expected Behavior

not sure, due to test name it may be valid behaviour in case of corrupted traffic.
however haproxy server was terminated on that which was not desired

### Steps to Reproduce the Behavior

run QUIC Interop on haproxy built with aws-lc

### What is your configuration?

```haproxy
no
```

### Output of `haproxy -vv`

```plain
usual QUIC Interop
```

**Comment by haproxyFred** [comment]
Not reproduced here at this time. For this one please check that your haproxy image embeds this commit: https://github.com/haproxytech/quic-dev/commit/e12620a8a909805755ae1e8b8552c187202a9f3f

Have a look to the output.txt file. The haproxy version is logged into this file.

**Comment by chipitsine** [comment]
for this I can provide "cloud repro"

https://github.com/chipitsine/quic-interop-aws-lc/actions/runs/10245027341

there are also logs in artifacts.


maybe you have no repro because of cached local s2n-quic image.

this issue is reproduced 100% for me either locally or GHA way


in output.txt (from artifacts above), haproxy version is

```
server  | haproxy version HAProxy version e12620a8a909805755ae1e8b8552c187202a9f3f 2024/07/24 - https://haproxy.org/
server  | Status: development branch - not safe for use in production.
```

**Comment by haproxyFred** [comment]
Perfect! So if you can reproduce this issue very often, would you mind testing this patch please? 
[bug.on.initial.pkt.txt](https://github.com/user-attachments/files/16493096/bug.on.initial.pkt.txt)

**Comment by haproxyFred** [comment]
In fact I could reproduce after having updated the correct client image (s2n-client). I have pushed a fix for this. That said, the handshakecorruption and handshakeloss very often fail (without haproxy crash) even with this patch for an undetermined reason at this time.

**Comment by chipitsine** [comment]
my "testing farm" is busy for the next few hours :(

(I planned to test locally)

**Comment by chipitsine** [comment]
it is fixed in master branch.
should I close this issue ?

**Comment by haproxyFred** [comment]
Must be backported.

**Comment by haproxyFred** [comment]
This issue must not be closed. It is partially fixed (no more crash).

**Comment by haproxyFred** [comment]
This issue should be fixed.

**Comment by chipitsine** [comment]
thanks!
