### ISSUE TITLE
HAProxy 3.2.5 + 3.2.6 with QUIC Frontend / Browser requests failing (ERR_QUIC_PROTOCOL_ERROR/ERROR_CONNECTION_CLOSED)

### ISSUE THREAD

**Issue by amsnek** [haproxy/haproxy#3164]
### Detailed Description of the Problem

After Upgrading from HAProxy 3.2.4 to HAProxy 3.2.5 (also tried with 3.2.6) Sites are not loading properly anymore.  The behavior seems a bit different in impact depending on the backend used (kibana worst, nginx bad, tomcats worked a bit better) but this could be testing coincidence.

Browsers failed to fetch elements from the site, Chrome for example shows ERR_QUIC_PROTOCOL_ERROR and then followed by ERROR_CONNECTION_CLOSED for following requests. HAPRoxy shows CDs for these requests, interestingly with http response status code 200 in the logs. These Requests usually take a while to process as well, ~30-50s, some of them are ended quickly on browser side with the ERR_CONN_CLOSED, others hang for a long while. 

Upgrading to 3.2.6 improved the Behaviour a bit, a tomcat backend starting working again as far as i can tell. No change kibana/nginx backends however with quic.

I tried using the same AWS-LC version i used in 3.2.4 (1.58.1) with 3.2.5 and 3.2.6. but this made no difference. 

switching to H2 and everything acts normally again. I did run haproxy in debug mode but nothing unusual was shown there. 

I can gladly provide logs or info, however I am not sure what to provide.

![Image](https://github.com/user-attachments/assets/cbbbe923-0394-4205-8ac5-5c1e76745848)

![Image](https://github.com/user-attachments/assets/63f1bcd7-9a50-46dd-8a6a-bd5df17f9d88)

### Expected Behavior

QUIC/H3 http requests being completed normally. 

### Steps to Reproduce the Behavior

Use H3 on a Frontend with 3.2.5/3.2.6 (ideally with kibana backend?)
open the login page 
observe ERR_CONN_CLOSED / not loading of site

### Do you have any idea what may have caused this?

it seems some change starting with 3.2.5 

### What is your configuration?

```haproxy
simplified configuration

defaults
        mode     http
        log     global
        balance leastconn
        option  redispatch
        option  abortonclose
        option  splice-auto
        option  tcp-smart-accept
        option  tcp-smart-connect

        timeout http-request     10s
        timeout http-keep-alive  60s
        timeout connect           5s
        timeout check             5s
        timeout queue            15s
        timeout server           60s
        timeout client           60s
        timeout client-fin       10s



frontend FE-KIBANA 
         bind 10.10.10.100:80
         bind 10.10.10.100:443 ssl crt-list /data/haproxy/ssl/crt-list.txt strict-sni
         bind quic4@10.10.10.100:443 ssl crt-list /data/haproxy/ssl/crt-list.txt strict-sni alpn h3

         http-after-response add-header alt-svc 'h3=":443"; ma=2592000' 
         redirect scheme https if !{ ssl_fc }
         default_backend BE-KIBANA



backend BE-KIBANA 
        http-check send meth GET uri /api/status ver HTTP/1.1 hdr Host host.tld hdr User-agent "haproxy"
        option httpchk
        http-check expect status 200
        default-server inter 15s fall 2 rise 2
        timeout check 2s

        server hostname 10.10.10.10:5601 ssl verify required ca-file bundle-ca.crt check check-alpn h2,http/1.1 alpn h2,http/1.1
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.2.5-ba0fd6b 2025/09/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2030.
Known bugs: http://www.haproxy.org/bugs/bugs-3.2.5.html
Running on: Linux 4.18.0-553.79.1.el8_10.x86_64 #1 SMP Fri Oct 3 10:58:12 EDT 2025 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Werror=format-security
  OPTIONS = USE_OPENSSL_AWSLC=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL +OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB +ACME

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=32, MAX_THREADS=1024, default=2).
Built with SSL library version : OpenSSL 1.1.1 (compatible; AWS-LC 1.61.4)
Running on SSL library version : AWS-LC 1.61.4
SSL library supports TLS extensions : yes
SSL library supports SNI : yes
SSL library FIPS mode : no
SSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
QUIC: connection socket-owner mode support : yes
QUIC: GSO emission support : no
Built with Lua version : Lua 5.4.8
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.46 2025-08-27
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-28)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=SPOP  side=BE     mux=SPOP  flags=HOL_RISK|NO_UPG
       spop : mode=SPOP  side=BE     mux=SPOP  flags=HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain

```

### Additional Information

self compiled haproxy
using aws-lc 
build against jemalloc (5.3.0)
for this test setup, there was no further component intercepting the traffic (same subnet)
behaviour improved on 3.2.6, a tomcat backend that was showing the same problems started working, however other backends still failed.

**Comment by haproxyFred** [comment]
What was the previous haproxy version which was working for QUIC on your side please?

**Comment by amsnek** [comment]
with 3.2.4 everything works as expected.

**Comment by haproxyFred** [comment]
Just for the record, there were no bug fixes merged into 3.2.6.

**Comment by amsnek** [comment]
it still occurs for me on 3.2.6, just seemingly "less often". this is probably purely anecdotal evidence. I still get the QUIC_PROTOCOL_ERRORs everywhere. will roll back to 3.2.4 for now, if there is any debug output I can provide, please let me know.

**Comment by haproxyFred** [comment]
Could you try to enable the QUIC traces as follows in your configuration file:

```
ring buf1
    size <size>
    format timed
    backing-file <filename>

traces
    trace quic sink buf1 level developer start now
    trace qmux sink buf1 level developer verbosity minimal start now
```

More information here:

https://docs.haproxy.org/3.2/configuration.html#12.1

**Comment by haproxyFred** [comment]
Perhaps this is in relation with this issue: https://github.com/haproxy/haproxy/issues/3141
Not sure...
So, yes it could be useful to verify there is no issue at all on your side with 3.2.4.

**Comment by amsnek** [comment]
I can confirm with 100% certainty that the issue does not occur on 3.2.4

attached the ring buffer with a request that had fails.
[ring-buffer-1.txt](https://github.com/user-attachments/files/23002556/ring-buffer-1.txt)

**Comment by haproxyFred** [comment]
Well, these traces do not seem to have caught any issue. I should have mentioned that the QUIC traces are very verbous. The handshake was not caught, that said it seems to have succeed because stream transfers have started (id 4), but captured only during about 20ms (only ACK received, no TX data by haproxy).

You should increase the size of the ring buffer and compress the output file. Let's say 10MB should be enough.

**Comment by amsnek** [comment]
will do, compressed files i may not attach however it seems. will try with 10mb

**Comment by amsnek** [comment]
10mb version this time: 

[ring-buf1.txt](https://github.com/user-attachments/files/23003318/ring-buf1.txt)

**Comment by haproxyFred** [comment]
Interesting. Just to be sure, could you send me such traces but with haproxy 3.2.4 please. I know this is boring, but the QUIC issues are difficult to diagnose.

**Comment by amsnek** [comment]
no problem. let me know if the 10mb was also sufficient in size when requests succeed. 

[ring-buf2.txt](https://github.com/user-attachments/files/23005253/ring-buf2.txt)

**Comment by haproxyFred** [comment]
Ok, Thank you. I have found a clue of the cause for such connection issues but I have not identified the commit which leads to such a bug yet.

**Comment by haproxyFred** [comment]
Ok I finally managed to reproduce this issue. I guess you have such a tuning setting in your conf:
`tune.quic.frontend.max-streams-bidi 10`

In fact there there is a patch which is missing in 3.2:

```
commit d7dea408c64c327cab6aebf4ccad93405b675565
Author: Frederic Lecaille <flecaille@haproxy.com>
Date:   Fri Sep 5 15:41:27 2025 +0200

    BUG/MINOR: quic: too short PADDING frame for too short packets
    
    This bug arrvived with this commit:
    
        MINOR: quic: centralize padding for HP sampling on packet building
    
    What was missed is the fact that at the centralization point for the
    PADDING frame to add for too short packet, <len> payload length  already includes
    <*pn_len> the packet number field length value.
    
    So when computing the length of the PADDING frame, the packet field length must
    not be considered and added to the payload length (<len>).
    
    This bug leaded too short PADDING frame to too short packets. This was the case,
    most of times with Application level packets with a 1-byte packet number field
    followed by a 1-byte PING frame. A 1-byte PADDING frame was added in this case
    in place of a correct 2-bytes PADDINF frame. The header packet protection of
    such packet could not be removed by the clients as for instance for ngtcp2 with
    such traces:
    
        I00001828 0x5a135c81e803f092c74bac64a85513b657 pkt could not decrypt packet number
    
    As the header protection could no be removed, the header keyupdate bit could also
    not be read by packet analyzers such as pyshark used during the keyupdate tests.
    
    No need to backport.
```

When this patch was produced, this one was not in 3.2 :
`MINOR: quic: centralize padding for HP sampling on packet building`
this is why it has been mentioned "no need to backport".

**Comment by amsnek** [comment]
that is correct! I am sorry, I should have provided more info or at least grepped all "quic" related stuff from the globals
I have
`tune.quic.frontend.max-streams-bidi 10`

what would be the proper approach? would removing or adjusting the number of stream be a viable approach? or will this be backported and patched?

thanks a lot for your efforts!

**Comment by haproxyFred** [comment]
A new 3.2 version will be produced soon with the backport.

**Comment by amsnek** [comment]
I can confirm, that the issue does not occur anymore for me with HAProxy 3.2.7 👍 
Thanks a lot!

**Comment by haproxyFred** [comment]
Thank you very much for you help @amsnek

**Comment by capflam** [comment]
Code in 2.8 is too different. It is safer to not backport the fix to 2.8 and 2.6. I'm closing
